version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:17'
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '04:37'
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    groups:
      official-actions-major:
        patterns:
          - 'actions/*'
        update-types:
          - major
      official-actions-routine:
        patterns:
          - 'actions/*'
        update-types:
          - minor
          - patch
