import {$,DAYS,PERIODS,courses,friends,esc,time,getSelectedFriend} from '../core/state.js';
import {commonFreeWithFriend} from './friends.js';

function freeBlocks(data=courses(),day=null){const out=[];for(let d=day||1;d<=(day||5);d++){const busy=new Set();data.filter(c=>c.day===d).forEach(c=>{for(let i=c.start;i<=c.end;i++)busy.add(i)});let start=null;for(let i=1;i<=9;i++){if(!busy.has(i)&&start===null)start=i;if((busy.has(i)||i===9)&&start!==null){const end=busy.has(i)?i-1:i;if(end-start+1>=2)out.push({day:d,start,end});start=null}}}return out}
const blockLabel=b=>`${DAYS[b.day-1][1]} ${PERIODS[b.start-1][0]}–${PERIODS[b.end-1][1]}`;
export function smartAnalysis(kind){const all=courses();let html='';if(kind==='stress'){const x=DAYS.map((_,i)=>({day:i+1,n:all.filter(c=>c.day===i+1).length,slots:all.filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0)})).sort((a,b)=>b.slots-a.slots||b.n-a.n)[0];html=`<b>${DAYS[x.day-1][1]}最滿。</b><br>共 ${x.n} 門、${x.slots} 節。${x.slots>=6?'這天不要再塞太重的讀書。':'可以把比較吃專注力的事放到其他長空檔。'}`}
else if(kind==='free'){const blocks=freeBlocks().sort((a,b)=>(b.end-b.start)-(a.end-a.start));html=blocks.length?`<b>比較完整的空堂：</b><br>${blocks.slice(0,4).map((b,i)=>`${i+1}. ${blockLabel(b)}（${b.end-b.start+1} 節）`).join('<br>')}`:'<b>沒有找到連續兩節以上的空堂。</b>'}
else if(kind==='study'){const blocks=freeBlocks().sort((a,b)=>(b.end-b.start)-(a.end-a.start)).slice(0,3);html=blocks.length?`<b>我會先排這幾段：</b><br>${blocks.map((b,i)=>`${i+1}. ${blockLabel(b)} → ${i===0?'最難的科目或作業':i===1?'複習＋題目':'整理筆記＋預習'}`).join('<br>')}`:'<b>課間空檔比較碎。</b><br>可以改用下課後 60–90 分鐘的固定時段。'}
else if(kind==='friend'){const f=friends().find(x=>x.id===getSelectedFriend())||friends()[0];if(!f)html='<b>還沒有好友。</b><br>先去「找人」加入朋友，我就能算共同空堂。';else{const blocks=commonFreeWithFriend(f,courses);html=blocks.length?`<b>你和 ${esc(f.name)} 的共同長空堂：</b><br>${blocks.slice(0,5).map((b,i)=>`${i+1}. ${blockLabel(b)}`).join('<br>')}`:'<b>目前沒找到連續兩節以上的共同空堂。</b>'}}
if($('#smartResult'))$('#smartResult').innerHTML=html;return $('#smartResult')?.innerText||''}
export function renderSmartOverview(){const box=$('#smartResult');if(!box)return;const all=courses(),max=DAYS.map((_,i)=>({d:i+1,s:all.filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0)})).sort((a,b)=>b.s-a.s)[0];box.innerHTML=`<b>這週 ${all.length} 門課。</b><br>${DAYS[max.d-1][1]}最滿，共 ${max.s} 節。`}
export function buildAIContext(){const all=courses().slice().sort((a,b)=>a.day-b.day||a.start-b.start),f=friends().find(x=>x.id===getSelectedFriend());const courseText=all.map(c=>`${c.day===0?'未排定':DAYS[c.day-1][1]} ${time(c)}｜${c.name}｜${c.teacher||'未填老師'}｜${c.room||'未填教室'}`).join('\n');const friendText=f?`\n目前選中的好友：${f.name}\n${(f.courses||[]).slice().sort((a,b)=>a.day-b.day||a.start-b.start).map(c=>`${c.day===0?'未排定':DAYS[c.day-1][1]} ${time(c)}｜${c.name}`).join('\n')}`:'';return `你是 Nolu 的安排助理。使用繁體中文與台灣常用語，回答要簡潔、具體，不知道的事情不要亂猜。\n\n使用者課表：\n${courseText}${friendText}\n\n節次：\n${PERIODS.map((p,i)=>`第${i+1}節 ${p[0]}-${p[1]}`).join('、')}`}
