import {$,$$,DAYS,PERIODS,courses,scheduleMeta,write,uid,esc,time,toast,getSelectedDay,setSelectedDay} from '../core/state.js';

function renderStats(){const all=courses(),scheduled=all.filter(c=>c.day>=1&&c.day<=5),todayDay=new Date().getDay(),today=scheduled.filter(c=>c.day===todayDay).sort((a,b)=>a.start-b.start);$('#today').textContent=today.length;$('#hours').textContent=scheduled.reduce((n,c)=>n+(c.end-c.start+1),0);$('#count').textContent=all.length;const h=new Date().getHours();$('#greet').textContent=(h<12?'早安':h<18?'下午好':'晚上好')+'，今天的課長這樣。';$('#summary').textContent=today.length?`今天 ${today.length} 門，第一堂是 ${today[0].name}，${PERIODS[today[0].start-1][0]} 開始。`:all.length?'今天沒有排課，時間是你的。':'課表還是空的。可以新增課程，或直接用圖片快速匯入。'}
function renderTabs(){const e=$('#tabs');if(!e)return;e.innerHTML=DAYS.map((d,i)=>`<button class="${getSelectedDay()===i+1?'on':''}" data-day="${i+1}">${d[1]}</button>`).join('');e.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{setSelectedDay(+b.dataset.day);renderTabs();renderMobile()})}
export function renderGrid(target='#grid',data=courses(),editable=true){const root=$(target);if(!root)return;let h='<div class="cell head" style="grid-column:1;grid-row:1"><b>節次</b><small>時間</small></div>';DAYS.forEach((d,i)=>h+=`<div class="cell head" style="grid-column:${i+2};grid-row:1"><b>${d[1]}</b><small>本週</small></div>`);PERIODS.forEach((p,i)=>{h+=`<div class="cell time" style="grid-column:1;grid-row:${i+2}"><b>${i+1}</b><small>${p[0]}<br>${p[1]}</small></div>`;DAYS.forEach((_,j)=>h+='<div class="cell" style="grid-column:'+(j+2)+';grid-row:'+(i+2)+'"></div>')});data.filter(c=>c.day>=1&&c.day<=5).forEach(c=>h+=`<div class="course-slot" style="grid-column:${c.day+1};grid-row:${c.start+1}/span ${c.end-c.start+1}"><article class="course ${c.color||'violet'}" data-course="${esc(c.id)}"><b>${esc(c.name)}</b><small>${esc(c.teacher||'未填老師')}<br>${esc(c.room||'未填教室')}<br>${time(c)}</small></article></div>`);root.innerHTML=h;if(editable)root.querySelectorAll('[data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderMobile(){const root=$('#mobile');if(!root)return;const list=courses().filter(c=>c.day===getSelectedDay()&&c.day>=1).sort((a,b)=>a.start-b.start);root.innerHTML=list.length?list.map(c=>`<article class="mobile-course ${c.color||'gray'}" data-course="${esc(c.id)}"><time>${time(c)}<br>第 ${c.start}${c.end>c.start?'–'+c.end:''} 節</time><div><b>${esc(c.name)}</b><p>${esc(c.teacher||'')} · ${esc(c.room||'')}</p></div></article>`).join(''):'<div class="project-note">這天沒有排課。</div>';root.querySelectorAll('[data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderMobileWeek(){const root=$('#mobileWeek');if(!root)return;const all=courses().filter(c=>c.day>=1&&c.day<=5);root.innerHTML=DAYS.map((d,i)=>{const cs=all.filter(c=>c.day===i+1).sort((x,y)=>x.start-y.start);return `<section class="week-day-block"><div class="week-day-title"><span>${d[1]}</span><small>${cs.length} 門課</small></div><div class="week-day-courses">${cs.length?cs.map(c=>`<article class="week-mini-course ${c.color||'gray'}" data-course="${esc(c.id)}"><time>${time(c)}<br>第${c.start}${c.end>c.start?'–'+c.end:''}節</time><div><b>${esc(c.name)}</b><br><small>${esc(c.teacher||'')} · ${esc(c.room||'')}</small></div></article>`).join(''):'<small>今天無課</small>'}</div></section>`}).join('');root.querySelectorAll('[data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderFloatingCourses(){const box=$('#floatingCourses');if(!box)return;const list=courses().filter(c=>c.day===0);box.innerHTML=list.length?list.map(c=>`<button class="project-note floating-note" data-course="${esc(c.id)}"><b>待定 / ${esc(c.name)}</b><span>${esc(c.teacher||'')} ${esc(c.room||'時間地點依最新公告')}</span></button>`).join(''):'';box.querySelectorAll('[data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
export function renderScheduleMeta(){const m=scheduleMeta(),title=m.title||[m.year?`${m.year} 學年度`:'',m.semester?`第 ${m.semester} 學期`:''].filter(Boolean).join('・');if($('#semesterLabel'))$('#semesterLabel').textContent=title||'我的學期';const bits=[m.school,m.className,m.credits?`${m.credits} 學分`:''].filter(Boolean);if($('#semesterMeta'))$('#semesterMeta').innerHTML=bits.length?bits.map(esc).join('<br>'):'自己的課表<br>匯入圖片後可自動辨識學期資訊'}
export function applyScheduleMode(mode=localStorage.getItem('puplan_schedule_mode')||'week'){document.body.classList.toggle('schedule-day-mode',mode==='day');$$('[data-schedule-mode]').forEach(b=>b.classList.toggle('on',b.dataset.scheduleMode===mode));localStorage.setItem('puplan_schedule_mode',mode)}
export function renderSchedule(){renderStats();renderTabs();renderGrid();renderMobileWeek();renderMobile();renderFloatingCourses();renderScheduleMeta();applyScheduleMode()}
function toggleCourseTimeFields(){const off=+$('#day').value===0;$('#start').disabled=off;$('#end').disabled=off}
export function openCourse(id){const c=id?courses().find(x=>x.id===id):null;$('#courseTitle').textContent=c?'編輯課程':'新增課程';$('#courseId').value=c?.id||'';$('#courseName').value=c?.name||'';$('#day').value=c?.day??getSelectedDay();$('#start').value=c?.start>0?c.start:3;$('#end').value=c?.end>0?c.end:4;toggleCourseTimeFields();$('#teacher').value=c?.teacher||'';$('#room').value=c?.room||'';$('#color').value=c?.color||['violet','blue','mint','orange','pink','lime','gray'][courses().length%7];$('#deleteCourse').hidden=!c;$('#courseDialog').showModal()}
export function initSchedule(){
  $('#day').innerHTML='<option value="0">未排定 / 依公告</option>'+DAYS.map((d,i)=>`<option value="${i+1}">${d[1]}</option>`).join('');
  ['start','end'].forEach(id=>$('#'+id).innerHTML=PERIODS.map((p,i)=>`<option value="${i+1}">第 ${i+1} 節　${p[0]}–${p[1]}</option>`).join(''));
  $('#day').addEventListener('change',toggleCourseTimeFields);
  $('#courseForm').onsubmit=e=>{e.preventDefault();const all=courses(),id=$('#courseId').value||uid(),s=+$('#start').value,en=+$('#end').value,d=+$('#day').value;if(d!==0&&en<s)return toast('結束節次不能早於開始');const item={id,name:$('#courseName').value.trim(),day:d,start:d===0?0:s,end:d===0?0:en,teacher:$('#teacher').value.trim(),room:$('#room').value.trim(),color:$('#color').value};const hit=d===0?null:all.find(c=>c.id!==id&&c.day===d&&!(en<c.start||s>c.end));if(hit&&!confirm(`與「${hit.name}」衝堂，仍要儲存？`))return;const i=all.findIndex(c=>c.id===id);i<0?all.push(item):all[i]=item;write('puplan_courses',all);document.dispatchEvent(new CustomEvent('puplan:courses-changed',{detail:all}));$('#courseDialog').close();renderSchedule();toast(i<0?'課程已新增':'課程已更新')};
  $('#deleteCourse').onclick=()=>{const id=$('#courseId').value,c=courses().find(x=>x.id===id);if(c&&confirm(`刪除「${c.name}」？`)){const next=courses().filter(x=>x.id!==id);write('puplan_courses',next);document.dispatchEvent(new CustomEvent('puplan:courses-changed',{detail:next}));$('#courseDialog').close();renderSchedule();toast('已刪除')}};
  $$('[data-schedule-mode]').forEach(b=>b.onclick=()=>applyScheduleMode(b.dataset.scheduleMode));
  $('#add').onclick=$('#mobileAdd').onclick=()=>openCourse();
  $('#importSchedule')?.addEventListener('click',()=>{$('#importDialog')?.showModal();document.dispatchEvent(new CustomEvent('puplan:import-opened'))});
}
