import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const enc=new TextEncoder(),dec=new TextDecoder();
const ALLOWED=new Set(['https://miiduoa.github.io','https://nolu.tw','https://www.nolu.tw','https://nolu-8r2.pages.dev','http://localhost:3000','http://localhost:5173','http://127.0.0.1:5500']);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
class ApiError extends Error{status:number;code:string;constructor(status:number,message:string,code='BAD_REQUEST'){super(message);this.status=status;this.code=code}}
function b64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(v:string){let n=String(v||'').replace(/-/g,'+').replace(/_/g,'/');while(n.length%4)n+='=';const r=atob(n),o=new Uint8Array(r.length);for(let i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o}
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
async function hmac(m:string){const k=await crypto.subtle.importKey('raw',enc.encode(KEY),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(m)))}
async function cv(salt:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(`nolu-session-v4:${salt}`)))).slice(0,22)}
async function requireUser(req:Request){const a=req.headers.get('authorization')||'',raw=a.startsWith('Bearer ')?a.slice(7):'';const[p,s,...x]=raw.split('.');if(!p||!s||x.length||!eq(await hmac(p),unb64(s)))throw new ApiError(401,'登入狀態無效','UNAUTHORIZED');let c:any;try{c=JSON.parse(dec.decode(unb64(p)))}catch{throw new ApiError(401,'登入狀態無效','UNAUTHORIZED')}const now=Math.floor(Date.now()/1000);if(c?.v!==4||!UUID.test(String(c.uid||''))||!c.exp||c.exp<now||!c.cv)throw new ApiError(401,'登入已過期','UNAUTHORIZED');const {data:u,error}=await db.from('puplan_app_users').select('id,email,display_name,username,avatar_data,bio,discoverable,role,profile_visibility,password_salt').eq('id',c.uid).maybeSingle();if(error)throw error;if(!u||await cv(String(u.password_salt||''))!==String(c.cv))throw new ApiError(401,'登入憑證已變更','SESSION_REVOKED');const {data:r}=await db.from('puplan_replica_state').select('enabled,seeded_at,credentials_synced_at').eq('user_id',u.id).maybeSingle();if(!r?.enabled||!r.seeded_at||!r.credentials_synced_at)throw new ApiError(503,'這個帳號尚未完成異地備援同步','STANDBY_NOT_SEEDED');return u}
function profile(u:any){return{id:u.id,display_name:u.display_name,username:u.username,avatar_data:u.avatar_data||'',bio:u.bio||'',discoverable:u.discoverable!==false,role:u.role||'user',profile_visibility:u.profile_visibility||'public'}}
function headers(origin:string){const h:any={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};if(ALLOWED.has(origin))h['Access-Control-Allow-Origin']=origin;return h}
function json(origin:string,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:headers(origin)})}
async function rateLimit(req:Request,action:string,limit:number,minutes:number){const ip=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'unknown').split(',')[0].trim(),key=b64(await hmac(`social-core:${ip}`)),since=new Date(Date.now()-minutes*60000).toISOString();const {count,error}=await db.from('puplan_app_rate_limits').select('id',{count:'exact',head:true}).eq('rate_key',key).eq('action',action).gte('created_at',since);if(error)throw error;if((count||0)>=limit)throw new ApiError(429,'操作太頻繁，請稍後再試','RATE_LIMITED');const ins=await db.from('puplan_app_rate_limits').insert({rate_key:key,action});if(ins.error)throw ins.error}
async function areFriends(a:string,b:string){const {data,error}=await db.from('puplan_app_friendships').select('id').eq('status','accepted').or(`and(requester_id.eq.${a},addressee_id.eq.${b}),and(requester_id.eq.${b},addressee_id.eq.${a})`).limit(1);if(error)throw error;return!!data?.length}
async function social(uid:string){const {data:rels,error}=await db.from('puplan_app_friendships').select('id,requester_id,addressee_id,status,created_at,updated_at').or(`requester_id.eq.${uid},addressee_id.eq.${uid}`).order('created_at',{ascending:false});if(error)throw error;const relationships=rels||[],ids=[...new Set(relationships.flatMap((r:any)=>[r.requester_id,r.addressee_id]).filter((id:string)=>id!==uid))];let profiles:any[]=[];if(ids.length){const r=await db.from('puplan_app_users').select('id,display_name,username,avatar_data,bio,discoverable,role,profile_visibility').in('id',ids);if(r.error)throw r.error;profiles=r.data||[]}const accepted=relationships.filter((r:any)=>r.status==='accepted'),friendIds=accepted.map((r:any)=>r.requester_id===uid?r.addressee_id:r.requester_id);let schedules:any[]=[];if(friendIds.length){const r=await db.from('puplan_app_semesters').select('user_id,courses,updated_at,semester_key,label').in('user_id',friendIds).eq('is_current',true);if(r.error)throw r.error;schedules=r.data||[]}const mr=await db.from('puplan_app_meetups').select('id,creator_id,invitee_id,kind,day,start_period,end_period,note,status,created_at,updated_at').or(`creator_id.eq.${uid},invitee_id.eq.${uid}`).order('created_at',{ascending:false}).limit(100);if(mr.error)throw mr.error;const pm=new Map(profiles.map((p:any)=>[p.id,p])),sm=new Map(schedules.map((s:any)=>[s.user_id,s]));const friends=friendIds.map((id:string)=>{const p:any=pm.get(id)||{display_name:'好友',username:'',avatar_data:'',bio:''},s:any=sm.get(id);return{id,name:p.display_name,username:p.username,avatar:p.avatar_data||'',bio:p.bio||'',courses:Array.isArray(s?.courses)?s.courses:[],semester_key:s?.semester_key||'',semester_label:s?.label||'',t:s?.updated_at||new Date().toISOString(),cloud:true}});return{relationships,profiles:profiles.map(profile),friends,meetups:mr.data||[]}}
function dirty(body:any={}){return{...body,standby_write:true,failback_pending:true,cloud_tier:'standby'}}
Deno.serve(async req=>{const origin=req.headers.get('origin')||'';if(req.method==='OPTIONS'){if(origin&&!ALLOWED.has(origin))return new Response('forbidden',{status:403});return new Response(null,{status:204,headers:headers(origin)})}if(req.method!=='POST')return json(origin,405,{error:'METHOD_NOT_ALLOWED'});if(origin&&!ALLOWED.has(origin))return json(origin,403,{error:'ORIGIN_NOT_ALLOWED'});try{const body=await req.json().catch(()=>({})),action=String(body.action||''),u=await requireUser(req);
  if(action==='social')return json(origin,200,{social:await social(u.id),cloud_tier:'standby'});
  if(action==='search_people'){await rateLimit(req,'search',120,5);const term=String(body.query||'').trim().replace(/^@/,'').replace(/[%,()]/g,'').slice(0,24);if(term.length<2)return json(origin,200,{people:[],cloud_tier:'standby'});const cols='id,display_name,username,avatar_data,bio,discoverable,role,profile_visibility';const [a,b]=await Promise.all([db.from('puplan_app_users').select(cols).eq('discoverable',true).ilike('display_name',`%${term}%`).neq('id',u.id).limit(10),db.from('puplan_app_users').select(cols).eq('discoverable',true).ilike('username',`%${term}%`).neq('id',u.id).limit(10)]);if(a.error)throw a.error;if(b.error)throw b.error;const map=new Map<string,any>();[...(a.data||[]),...(b.data||[])].forEach((p:any)=>map.set(p.id,p));return json(origin,200,{people:[...map.values()].slice(0,10).map(profile),cloud_tier:'standby'});}
  if(action==='send_request'){const target=String(body.user_id||'');if(!UUID.test(target)||target===u.id)throw new ApiError(400,'好友資料不正確');const t=await db.from('puplan_app_users').select('id,discoverable').eq('id',target).maybeSingle();if(t.error)throw t.error;if(!t.data||t.data.discoverable===false)throw new ApiError(404,'找不到這個使用者');const existing=await db.from('puplan_app_friendships').select('id').or(`and(requester_id.eq.${u.id},addressee_id.eq.${target}),and(requester_id.eq.${target},addressee_id.eq.${u.id})`).limit(1);if(existing.error)throw existing.error;if(existing.data?.length)throw new ApiError(409,'你們已經有好友關係或邀請','RELATION_EXISTS');const r=await db.from('puplan_app_friendships').insert({requester_id:u.id,addressee_id:target,status:'pending'});if(r.error)throw r.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='accept_request'){const id=Number(body.friendship_id);if(!Number.isSafeInteger(id))throw new ApiError(400,'好友邀請資料不正確');const r=await db.from('puplan_app_friendships').select('id').eq('id',id).eq('addressee_id',u.id).eq('status','pending').maybeSingle();if(r.error)throw r.error;if(!r.data)throw new ApiError(404,'找不到這筆好友邀請');const x=await db.from('puplan_app_friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',id);if(x.error)throw x.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='decline_request'){const id=Number(body.friendship_id);if(!Number.isSafeInteger(id))throw new ApiError(400,'好友邀請資料不正確');const r=await db.from('puplan_app_friendships').delete().eq('id',id).eq('addressee_id',u.id).eq('status','pending');if(r.error)throw r.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='remove_friend'){const target=String(body.user_id||'');if(!UUID.test(target)||target===u.id)throw new ApiError(400,'好友資料不正確');const [a,b]=await Promise.all([db.from('puplan_app_friendships').select('id').eq('requester_id',u.id).eq('addressee_id',target),db.from('puplan_app_friendships').select('id').eq('requester_id',target).eq('addressee_id',u.id)]);if(a.error)throw a.error;if(b.error)throw b.error;const ids=[...(a.data||[]),...(b.data||[])].map((x:any)=>x.id);if(ids.length){const r=await db.from('puplan_app_friendships').delete().in('id',ids);if(r.error)throw r.error}return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='create_meetup'){await rateLimit(req,'meetup',30,10);const target=String(body.user_id||'');if(!UUID.test(target)||target===u.id)throw new ApiError(400,'好友資料不正確');if(!(await areFriends(u.id,target)))throw new ApiError(403,'只有好友可以互相發邀約');const kind=String(body.kind||''),day=Number(body.day),start=Number(body.start_period),end=Number(body.end_period),note=String(body.note||'').trim().slice(0,120);if(!['meal','study'].includes(kind))throw new ApiError(400,'邀約類型不正確');if(!Number.isInteger(day)||day<1||day>5||!Number.isInteger(start)||start<1||start>13||!Number.isInteger(end)||end<start||end>13)throw new ApiError(400,'邀約時間不正確');const r=await db.from('puplan_app_meetups').insert({creator_id:u.id,invitee_id:target,kind,day,start_period:start,end_period:end,note,status:'pending'});if(r.error)throw r.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='respond_meetup'){const id=String(body.meetup_id||''),decision=String(body.decision||'');if(!UUID.test(id)||!['accepted','declined'].includes(decision))throw new ApiError(400,'回覆不正確');const m=await db.from('puplan_app_meetups').select('id').eq('id',id).eq('invitee_id',u.id).eq('status','pending').maybeSingle();if(m.error)throw m.error;if(!m.data)throw new ApiError(404,'找不到這筆邀約');const r=await db.from('puplan_app_meetups').update({status:decision,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  if(action==='cancel_meetup'){const id=String(body.meetup_id||'');if(!UUID.test(id))throw new ApiError(400,'邀約資料不正確');const r=await db.from('puplan_app_meetups').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',id).eq('creator_id',u.id).in('status',['pending','accepted']);if(r.error)throw r.error;return json(origin,200,dirty({ok:true,social:await social(u.id)}));}
  throw new ApiError(400,'未知操作','UNKNOWN_ACTION');
}catch(e){if(e instanceof ApiError)return json(origin,e.status,{error:e.code,message:e.message,cloud_tier:'standby'});console.error('standby social core failed',String(e));return json(origin,500,{error:'SERVER_ERROR',message:'備援社交服務暫時忙碌',cloud_tier:'standby'})}});
