import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { ed25519 } from 'npm:@noble/curves@1.8.2/ed25519';
import { assertCredentialCurrent, SessionError, verifySignedSessionV4 } from './session-v4.ts';

const URL=Deno.env.get('SUPABASE_URL')||'';
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const SELF='ltfurqaspqsvswmebyzw',PRIMARY='hrrmkrayvrgnwcroyttp';
const PRIMARY_INGEST=`https://${PRIMARY}.supabase.co/functions/v1/pu-plan-media-ingest-v1`;
const DOMAIN='nolu-failback-ed25519-v1-20260911';
const BUCKET='puplan-media';
const enc=new TextEncoder();
const ALLOWED=new Set(['https://miiduoa.github.io','https://nolu.tw','https://www.nolu.tw','https://nolu-8r2.pages.dev','http://localhost:3000','http://localhost:5173','http://127.0.0.1:5500']);
class ApiError extends Error{status:number;code:string;constructor(status:number,message:string,code:string){super(message);this.status=status;this.code=code}}
function b64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function cors(origin:string){const h:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};if(ALLOWED.has(origin))h['Access-Control-Allow-Origin']=origin;return h}
function json(origin:string,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:cors(origin)})}
function sessionError(error:unknown){return error instanceof SessionError?new ApiError(401,error.message,error.code):new ApiError(401,'登入狀態無效，請重新登入','UNAUTHORIZED')}
async function user(req:Request){const a=req.headers.get('authorization')||'',token=a.startsWith('Bearer ')?a.slice(7):'';let session;try{session=await verifySignedSessionV4(token,KEY)}catch(error){throw sessionError(error)}const {data,error}=await db.from('puplan_app_users').select('id,password_salt').eq('id',session.uid).maybeSingle();if(error)throw error;if(!data?.id)throw new ApiError(401,'找不到帳號','UNAUTHORIZED');try{await assertCredentialCurrent(session,data.password_salt||'')}catch(error){throw sessionError(error)}return String(data.id)}
async function signingSeed(){if(!KEY||!URL.includes(SELF))throw new ApiError(503,'signing unavailable','MEDIA_FAILBACK_UNAVAILABLE');return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(`${DOMAIN}:${KEY}`)))}
async function transfer(row:any){const path=String(row.storage_path||''),mime=String(row.mime_type||''),size=Number(row.size_bytes||0);if(!path||!mime||!size)throw new ApiError(409,'媒體中繼資料不完整','MEDIA_INTEGRITY');const signed=await db.storage.from(BUCKET).createSignedUrl(path,300);if(signed.error||!signed.data?.signedUrl)throw new ApiError(503,'無法讀取備援媒體','MEDIA_SOURCE_UNAVAILABLE');const now=new Date(),payload={v:1,kind:'media-failback',iss:SELF,aud:PRIMARY,iat:now.toISOString(),exp:new Date(now.getTime()+120000).toISOString(),nonce:crypto.randomUUID(),uid:String(row.owner_id),storage_path:path,mime,size,source_url:signed.data.signedUrl};const encoded=b64(enc.encode(JSON.stringify(payload))),signature=b64(ed25519.sign(enc.encode(encoded),await signingSeed()));const response=await fetch(PRIMARY_INGEST,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({envelope:`${encoded}.${signature}`}),cache:'no-store',signal:AbortSignal.timeout(95000)});const out=await response.json().catch(()=>({}));if(!response.ok||out.ok!==true)throw new ApiError(response.status>=500?503:response.status,out.message||'媒體回灌失敗',out.error||'MEDIA_FAILBACK_FAILED')}
Deno.serve(async req=>{const origin=req.headers.get('origin')||'';if(req.method==='OPTIONS'){if(origin&&!ALLOWED.has(origin))return new Response('forbidden',{status:403});return new Response(null,{status:204,headers:cors(origin)})}if(req.method==='GET')return json(origin,200,{ok:true,service:'pu-plan-media-failback-v1',role:'standby',protocol:1});if(req.method!=='POST')return json(origin,405,{error:'METHOD_NOT_ALLOWED'});if(origin&&!ALLOWED.has(origin))return json(origin,403,{error:'ORIGIN_NOT_ALLOWED'});try{const uid=await user(req),body=await req.json().catch(()=>({})),offset=Math.max(0,Number(body.offset)||0),limit=Math.max(1,Math.min(4,Number(body.limit)||2));const {data,error}=await db.from('puplan_app_post_media').select('id,owner_id,storage_path,mime_type,size_bytes,created_at').eq('owner_id',uid).order('created_at',{ascending:true}).range(offset,offset+limit);if(error)throw error;const rows=data||[];for(const row of rows)await transfer(row);return json(origin,200,{ok:true,transferred:rows.length,next_offset:rows.length===limit?offset+rows.length:null,complete:rows.length<limit})}catch(error){if(error instanceof ApiError)return json(origin,error.status,{error:error.code,message:error.message});console.error('media failback failed');return json(origin,503,{error:'MEDIA_FAILBACK_UNAVAILABLE',message:'媒體回灌暫時無法完成'})}});
