import {cleanAvatar} from './core/state.js';
const ADMIN_API='https://hrrmkrayvrgnwcroyttp.supabase.co/functions/v1/pu-plan-admin';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=window.PUPLAN_APP;
const token=()=>localStorage.getItem('puplan_session')||'';
const esc=s=>app?.esc?.(String(s??''))||String(s??'');
const fmtTime=v=>v?new Date(v).toLocaleString('zh-TW',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
let userOffset=0,userQuery='',postMode='post',postOffset=0,chatOffset=0,currentConversation='';

async function request(action,payload={}){
  const res=await fetch(ADMIN_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`},body:JSON.stringify({action,...payload})});
  const data=await res.json().catch(()=>({}));
  if(!res.ok)throw new Error(data.message||'管理功能暫時無法使用');
  return data;
}
function notice(text,type=''){return `<div class="admin-message ${type}">${esc(text)}</div>`}
function avatar(u){const src=cleanAvatar(u?.avatar_data||'');return src?`<span class="admin-avatar"><img src="${esc(src)}" alt=""></span>`:`<span class="admin-avatar">${esc((u?.display_name||'?')[0])}</span>`}
function confirmAction(text){return window.confirm(text)}

function install(){
  if($('#admin'))return;
  const section=document.createElement('section');section.id='admin';section.className='view admin-view';
  section.innerHTML=`<div class="admin-head"><div><h2>網站管理</h2><p>管理會員、貼文、留言與聊天內容。每次管理操作都會留下紀錄。</p></div><span class="admin-chip">管理員</span></div><div class="admin-tabs"><button class="on" data-admin-tab="overview">營運總覽</button><button data-admin-tab="users">會員管理</button><button data-admin-tab="posts">貼文與留言</button><button data-admin-tab="chats">聊天室</button></div><div id="adminBody"></div>`;
  $('.main')?.append(section);
  const nav=$('.nav');if(nav&&!nav.querySelector('[data-admin-open]')){const b=document.createElement('button');b.dataset.adminOpen='1';b.textContent='06　網站管理';nav.append(b);b.onclick=open}
  const settings=$('#settings .settings');if(settings&&!$('#adminAccessCard')){const card=document.createElement('article');card.id='adminAccessCard';card.className='setting-card admin-access-card';card.innerHTML='<h3>網站管理</h3><p>管理會員與社群內容，並查看網站使用狀況。</p><button class="btn primary" id="openAdminPanel" style="width:100%">進入管理頁面</button>';settings.append(card);$('#openAdminPanel').onclick=open}
  section.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.adminTab));
}
function open(){
  $$('.view').forEach(x=>x.classList.toggle('on',x.id==='admin'));$$('[data-view],[data-community-open]').forEach(x=>x.classList.remove('on'));$$('[data-admin-open]').forEach(x=>x.classList.add('on'));
  if($('#title'))$('#title').textContent='網站管理';if($('#kicker'))$('#kicker').textContent='';if($('#add'))$('#add').style.visibility='hidden';switchTab('overview')
}
function switchTab(tab){$$('[data-admin-tab]').forEach(b=>b.classList.toggle('on',b.dataset.adminTab===tab));if(tab==='overview')overview();if(tab==='users')users();if(tab==='posts')posts();if(tab==='chats')chats()}

async function overview(){const root=$('#adminBody');root.innerHTML=notice('正在整理網站狀況…');try{const d=await request('overview'),s=d.stats||{};root.innerHTML=`<div class="admin-stats">${[['會員',s.users],['貼文',s.posts],['留言',s.replies],['聊天訊息',s.messages],['聊天室',s.conversations],['好友關係',s.friendships],['學期資料',s.semesters],['照片與影片',s.media]].map(([k,v])=>`<article><b>${Number(v||0).toLocaleString()}</b><span>${k}</span></article>`).join('')}</div><div class="admin-note"><b>管理原則</b><p>這裡只顯示營運需要的內容，不會顯示密碼、救援碼或其他登入機密。管理貼文、留言與聊天內容時，系統會留下操作紀錄。</p></div>`}catch(e){root.innerHTML=notice(e.message,'error')}}

async function users(query=userQuery,offset=userOffset){userQuery=query;userOffset=Math.max(0,offset);const root=$('#adminBody');root.innerHTML=`<div class="admin-toolbar"><input id="adminUserSearch" placeholder="搜尋姓名、帳號或 Email" value="${esc(query)}"><button class="btn" id="adminUserSearchBtn">搜尋</button></div><div id="adminUsersList">${notice('正在讀取會員資料…')}</div><div id="adminUserPager"></div><div id="adminUserDetail"></div>`;$('#adminUserSearchBtn').onclick=()=>users($('#adminUserSearch').value.trim(),0);$('#adminUserSearch').onkeydown=e=>{if(e.key==='Enter')users(e.currentTarget.value.trim(),0)};try{const limit=50,d=await request('users',{query,limit,offset:userOffset}),list=$('#adminUsersList');list.className='admin-users-list';list.innerHTML=(d.users||[]).map(u=>`<button class="admin-user-row" data-user="${u.id}">${avatar(u)}<span class="admin-user-copy"><b>${esc(u.display_name)}</b><small>@${esc(u.username)} · ${esc(u.email)}</small></span><em>${u.role==='admin'?'管理員':u.profile_visibility==='private'?'私人帳號':'公開帳號'}</em></button>`).join('')||notice('找不到符合的會員');list.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>userDetail(b.dataset.user));const total=Number(d.total||0);$('#adminUserPager').innerHTML=pager(total,userOffset,limit,'user');bindPager('user',total,userOffset,limit)}catch(e){$('#adminUsersList').innerHTML=notice(e.message,'error')}}
function pager(total,offset,limit,type){if(total<=limit)return'';return`<div class="admin-pager"><button class="btn" data-prev-${type} ${offset===0?'disabled':''}>上一頁</button><span>${Math.min(total,offset+1)}–${Math.min(total,offset+limit)}，共 ${total} 位</span><button class="btn" data-next-${type} ${offset+limit>=total?'disabled':''}>下一頁</button></div>`}
function bindPager(type,total,offset,limit){const prev=$(`[data-prev-${type}]`),next=$(`[data-next-${type}]`);if(type==='user'){if(prev)prev.onclick=()=>users(userQuery,Math.max(0,offset-limit));if(next)next.onclick=()=>users(userQuery,offset+limit)}if(type==='post'){if(prev)prev.onclick=()=>posts(postMode,Math.max(0,offset-limit));if(next)next.onclick=()=>posts(postMode,offset+limit)}if(type==='chat'){if(prev)prev.onclick=()=>chats(Math.max(0,offset-limit));if(next)next.onclick=()=>chats(offset+limit)}}

async function userDetail(id){const box=$('#adminUserDetail');box.innerHTML=notice('正在讀取會員資料…');try{const d=await request('user_detail',{user_id:id}),u=d.user;const joined=fmtTime(u.created_at),postCount=(d.posts||[]).filter(x=>!x.parent_id&&!x.deleted_at).length,replyCount=(d.posts||[]).filter(x=>x.parent_id&&!x.deleted_at).length;box.innerHTML=`<section class="admin-detail-card"><div class="admin-detail-head">${avatar(u)}<div><h3>${esc(u.display_name)}</h3><p>@${esc(u.username)} · ${esc(u.email)}</p><small>加入時間：${joined}</small></div></div><div class="admin-summary-grid"><span><b>${(d.semesters||[]).length}</b>學期</span><span><b>${postCount}</b>貼文</span><span><b>${replyCount}</b>留言</span><span><b>${(d.memberships||[]).length}</b>聊天室</span></div><div class="admin-control-card"><h4>帳號隱私</h4><label><span>個人頁</span><select id="adminUserVisibility"><option value="public" ${u.profile_visibility==='public'?'selected':''}>公開</option><option value="private" ${u.profile_visibility==='private'?'selected':''}>私人</option></select></label><label class="admin-check"><input type="checkbox" id="adminUserDiscoverable" ${u.discoverable!==false?'checked':''}><span>允許其他人搜尋到這個帳號</span></label><button class="btn" id="saveAdminUserPrivacy">儲存設定</button></div><div class="admin-member-content"><h4>近期貼文與留言</h4>${(d.posts||[]).slice(0,20).map(p=>`<div class="admin-mini-content"><span>${p.parent_id?'留言':'貼文'} · ${fmtTime(p.created_at)}</span><p>${esc(p.body||'（已下架）')}</p></div>`).join('')||'<p class="admin-muted">沒有近期內容</p>'}</div></section>`;$('#saveAdminUserPrivacy').onclick=async()=>{try{await request('set_user_privacy',{user_id:id,profile_visibility:$('#adminUserVisibility').value,discoverable:$('#adminUserDiscoverable').checked});app.toast('會員設定已更新');userDetail(id)}catch(e){app.toast(e.message)}};box.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){box.innerHTML=notice(e.message,'error')}}

async function posts(mode=postMode,offset=postOffset){postMode=mode;postOffset=Math.max(0,offset);const root=$('#adminBody');root.innerHTML=`<div class="admin-content-switch"><button class="${mode==='post'?'on':''}" data-content-mode="post">貼文</button><button class="${mode==='reply'?'on':''}" data-content-mode="reply">留言</button></div><div id="adminContentList">${notice('正在讀取內容…')}</div><div id="adminPostPager"></div>`;$$('[data-content-mode]').forEach(b=>b.onclick=()=>posts(b.dataset.contentMode,0));try{const limit=50,d=await request('posts',{kind:mode,limit,offset:postOffset}),list=$('#adminContentList');list.className='admin-content-list';list.innerHTML=(d.items||[]).map(p=>`<article class="admin-content-row ${p.deleted_at?'removed':''}"><div class="admin-content-meta">${avatar(p.author)}<div><b>${esc(p.author?.display_name||'使用者')}</b><small>@${esc(p.author?.username||'')} · ${fmtTime(p.created_at)} · ${p.visibility==='private'?'僅好友':'公開'}</small></div><span>${p.deleted_at?'已下架':mode==='reply'?'留言':'貼文'}</span></div><p>${esc(p.body||'（沒有文字內容）')}</p><div class="admin-row-actions">${p.deleted_at?`<button class="btn" data-restore-post="${p.id}">恢復顯示</button>`:`<button class="btn danger" data-remove-post="${p.id}">下架${mode==='reply'?'留言':'貼文'}</button>`}</div></article>`).join('')||notice(mode==='reply'?'目前沒有留言':'目前沒有貼文');list.querySelectorAll('[data-remove-post]').forEach(b=>b.onclick=()=>moderatePost(b.dataset.removePost,'remove'));list.querySelectorAll('[data-restore-post]').forEach(b=>b.onclick=()=>moderatePost(b.dataset.restorePost,'restore'));const total=Number(d.total||0);$('#adminPostPager').innerHTML=pager(total,postOffset,limit,'post');bindPager('post',total,postOffset,limit)}catch(e){$('#adminContentList').innerHTML=notice(e.message,'error')}}
async function moderatePost(id,mode){const wording=mode==='remove'?'確定要下架這則內容嗎？使用者之後會看不到它。':'確定要恢復這則內容嗎？';if(!confirmAction(wording))return;try{await request('moderate_post',{id,mode});app.toast(mode==='remove'?'內容已下架':'內容已恢復');posts(postMode,postOffset)}catch(e){app.toast(e.message)}}

async function chats(offset=chatOffset){chatOffset=Math.max(0,offset);currentConversation='';const root=$('#adminBody');root.innerHTML=`<div class="admin-chat-layout"><div><h3>聊天室</h3><div id="adminChatList">${notice('正在讀取聊天室…')}</div><div id="adminChatPager"></div></div><div id="adminChatDetail" class="admin-chat-detail">選一個聊天室查看內容。</div></div>`;try{const limit=50,d=await request('conversations',{limit,offset:chatOffset}),list=$('#adminChatList');list.className='admin-chat-list';list.innerHTML=(d.items||[]).map(c=>`<button class="admin-chat-row" data-chat="${c.id}"><span><b>${esc(c.title||'未命名聊天室')}</b><small>${c.kind==='direct'?'私訊':'群組聊天'} · ${c.member_count} 位成員 · ${c.message_count} 則訊息</small></span><em>${fmtTime(c.updated_at)}</em></button>`).join('')||notice('目前沒有聊天室');list.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>chatDetail(b.dataset.chat));const total=Number(d.total||0);$('#adminChatPager').innerHTML=pager(total,chatOffset,limit,'chat');bindPager('chat',total,chatOffset,limit)}catch(e){$('#adminChatList').innerHTML=notice(e.message,'error')}}
async function chatDetail(id){currentConversation=id;const box=$('#adminChatDetail');box.innerHTML=notice('正在讀取對話…');try{const d=await request('conversation_detail',{id}),c=d.conversation;box.innerHTML=`<div class="admin-chat-head"><div><h3>${esc(c.title||'未命名聊天室')}</h3><p>${c.kind==='direct'?'私訊':'群組聊天'} · ${(d.members||[]).length} 位成員</p></div>${c.kind==='group'?'<button class="btn" id="renameAdminChat">修改名稱</button>':''}</div><div class="admin-chat-members"><b>成員</b><div>${(d.members||[]).map(m=>`<span>${esc(m.user?.display_name||'使用者')} <small>@${esc(m.user?.username||'')}</small></span>`).join('')}</div></div><div class="admin-message-list">${(d.messages||[]).map(m=>`<div class="admin-message-row"><div><b>${esc(m.sender?.display_name||'使用者')}</b><small>${fmtTime(m.created_at)}${m.edited_at?' · 已編輯':''}</small></div><p>${esc(m.body)}</p>${m.body!=='此訊息已由管理員移除'?`<button data-remove-message="${m.id}">移除訊息</button>`:'<span class="admin-removed-label">已由管理員移除</span>'}</div>`).join('')||'<p class="admin-muted">聊天室目前沒有訊息</p>'}</div>`;if($('#renameAdminChat'))$('#renameAdminChat').onclick=async()=>{const title=prompt('輸入新的聊天室名稱',c.title||'');if(!title?.trim())return;try{await request('rename_conversation',{id,title:title.trim()});app.toast('聊天室名稱已更新');chatDetail(id)}catch(e){app.toast(e.message)}};box.querySelectorAll('[data-remove-message]').forEach(b=>b.onclick=async()=>{if(!confirmAction('確定要移除這則訊息嗎？原位置會顯示「此訊息已由管理員移除」。'))return;try{await request('remove_message',{id:b.dataset.removeMessage});app.toast('訊息已移除');chatDetail(id)}catch(e){app.toast(e.message)}})}catch(e){box.innerHTML=notice(e.message,'error')}}

async function boot(){if(!token())return;try{const me=await request('whoami');if(me.is_admin)install()}catch{}}
setTimeout(boot,900);document.addEventListener('puplan:profile-changed',()=>setTimeout(boot,180));
window.PUPLAN_ADMIN={open};
