const ADMIN_API='https://hrrmkrayvrgnwcroyttp.supabase.co/functions/v1/pu-plan-admin';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=window.PUPLAN_APP;
const token=()=>localStorage.getItem('puplan_session')||'';
const esc=s=>app?.esc?.(String(s??''))||String(s??'');
let adminUserQuery='',adminUserOffset=0,adminDatasetName='users',adminDatasetOffset=0;
async function adminRequest(action,payload={}){const res=await fetch(ADMIN_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`},body:JSON.stringify({action,...payload})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'管理功能無法使用');return data}
function pretty(v){if(v===null||v===undefined)return'—';if(typeof v==='object')return JSON.stringify(v,null,2);return String(v)}
function installAdmin(){if($('#admin'))return;const section=document.createElement('section');section.id='admin';section.className='view admin-view';section.innerHTML=`<div class="admin-head"><div><h2>系統管理</h2><p>查看 PU/PLAN 使用者與系統資料。所有管理查詢都會留下稽核紀錄。</p></div><span class="admin-chip">ADMIN</span></div><div class="admin-tabs"><button class="on" data-admin-tab="overview">總覽</button><button data-admin-tab="users">使用者</button><button data-admin-tab="data">所有資料</button></div><div id="adminBody"></div>`;document.querySelector('.main')?.append(section);const nav=$('.nav');if(nav&&!nav.querySelector('[data-admin-open]')){const b=document.createElement('button');b.dataset.adminOpen='1';b.textContent='06　系統管理';nav.append(b);b.onclick=showAdmin}const settings=$('#settings .settings');if(settings&&!$('#adminAccessCard')){const card=document.createElement('article');card.id='adminAccessCard';card.className='setting-card admin-access-card';card.innerHTML='<h3>系統管理</h3><p>管理員可查看 PU/PLAN 使用者與營運資料，所有查詢都會留下稽核紀錄。</p><button class="btn primary" id="openAdminPanel" style="width:100%">開啟系統管理</button>';settings.append(card);$('#openAdminPanel').onclick=showAdmin}section.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.adminTab));}
function showAdmin(){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id==='admin'));document.querySelectorAll('[data-view],[data-community-open]').forEach(x=>x.classList.remove('on'));document.querySelectorAll('[data-admin-open]').forEach(x=>x.classList.add('on'));if($('#title'))$('#title').textContent='系統管理';if($('#kicker'))$('#kicker').textContent='';if($('#add'))$('#add').style.visibility='hidden';switchTab('overview')}
function switchTab(tab){$$('[data-admin-tab]').forEach(b=>b.classList.toggle('on',b.dataset.adminTab===tab));if(tab==='overview')renderOverview();if(tab==='users')renderUsers();if(tab==='data')renderDatasetShell()}
async function renderOverview(){const root=$('#adminBody');root.innerHTML='<div class="admin-loading">讀取中…</div>';try{const data=await adminRequest('overview'),s=data.stats||{};root.innerHTML=`<div class="admin-stats">${[['使用者',s.users],['貼文',s.posts],['留言',s.replies],['訊息',s.messages],['聊天室',s.conversations],['好友關係',s.friendships],['學期資料',s.semesters],['媒體',s.media]].map(([k,v])=>`<article><b>${Number(v||0).toLocaleString()}</b><span>${k}</span></article>`).join('')}</div><div class="admin-note">管理控制台可查看所有 PU/PLAN 應用資料，但不會顯示密碼雜湊、密碼 salt 或救援碼雜湊等認證秘密。</div>`}catch(e){root.innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
async function renderUsers(query=adminUserQuery,offset=adminUserOffset){adminUserQuery=query;adminUserOffset=Math.max(0,offset);const root=$('#adminBody');root.innerHTML=`<div class="admin-users-toolbar"><input id="adminUserSearch" placeholder="搜尋名字、@帳號或 Email" value="${esc(query)}"><button class="btn" id="adminUserSearchBtn">搜尋</button></div><div id="adminUsersList" class="admin-users-list"><div class="admin-loading">讀取中…</div></div><div id="adminUserPager"></div><div id="adminUserDetail"></div>`;$('#adminUserSearchBtn').onclick=()=>renderUsers($('#adminUserSearch').value.trim(),0);$('#adminUserSearch').onkeydown=e=>{if(e.key==='Enter')renderUsers(e.currentTarget.value.trim(),0)};try{const limit=100,data=await adminRequest('users',{query,limit,offset:adminUserOffset});const list=$('#adminUsersList');list.innerHTML=(data.users||[]).map(u=>`<button class="admin-user-row" data-admin-user="${u.id}">${u.avatar_data?`<span class="admin-avatar"><img src="${esc(u.avatar_data)}" alt=""></span>`:`<span class="admin-avatar">${esc((u.display_name||'?')[0])}</span>`}<span><b>${esc(u.display_name)}</b><small>@${esc(u.username)} · ${esc(u.email)}</small></span><em>${u.role==='admin'?'管理員':u.profile_visibility==='private'?'私人':'公開'}</em></button>`).join('')||'<div class="admin-empty">找不到使用者</div>';list.querySelectorAll('[data-admin-user]').forEach(b=>b.onclick=()=>loadUserDetail(b.dataset.adminUser));const total=Number(data.total||0),pager=$('#adminUserPager');pager.innerHTML=`<div class="admin-pager"><button class="btn" id="adminPrevUsers" ${adminUserOffset===0?'disabled':''}>上一頁</button><span>${Math.min(total,adminUserOffset+1)}–${Math.min(total,adminUserOffset+limit)} / ${total}</span><button class="btn" id="adminNextUsers" ${adminUserOffset+limit>=total?'disabled':''}>下一頁</button></div>`;$('#adminPrevUsers').onclick=()=>renderUsers(adminUserQuery,Math.max(0,adminUserOffset-limit));$('#adminNextUsers').onclick=()=>renderUsers(adminUserQuery,adminUserOffset+limit)}catch(e){$('#adminUsersList').innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
function renderObjectCards(title,rows){if(!rows||!rows.length)return`<section class="admin-data-group"><h4>${title}</h4><div class="admin-empty">沒有資料</div></section>`;return`<section class="admin-data-group"><h4>${title} <span>${rows.length}</span></h4><div class="admin-json-list">${rows.slice(0,100).map(r=>`<pre>${esc(pretty(r))}</pre>`).join('')}</div></section>`}
async function loadUserDetail(id){const box=$('#adminUserDetail');box.innerHTML='<div class="admin-loading">讀取使用者資料…</div>';try{const d=await adminRequest('user_detail',{user_id:id});box.innerHTML=`<div class="admin-detail-head"><div><h3>${esc(d.user.display_name)}</h3><p>@${esc(d.user.username)} · ${esc(d.user.email)} · ${d.user.profile_visibility==='private'?'私人帳號':'公開帳號'}</p></div><span>${d.user.role==='admin'?'ADMIN':'USER'}</span></div>${renderObjectCards('學期',d.semesters)}${renderObjectCards('課表備份',d.schedule?[d.schedule]:[])}${renderObjectCards('好友關係',d.friendships)}${renderObjectCards('邀約',d.meetups)}${renderObjectCards('貼文與留言',d.posts)}${renderObjectCards('按讚',d.likes)}${renderObjectCards('聊天室成員資格',d.memberships)}${renderObjectCards('聊天室',d.conversations)}${renderObjectCards('已傳送訊息',d.messages_sent)}`;box.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){box.innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
const DATASETS=['users','semesters','schedules','friendships','meetups','conversations','conversation_members','messages','posts','post_media','post_likes','admin_audit'];
function renderDatasetShell(){const root=$('#adminBody');root.innerHTML=`<div class="admin-dataset-toolbar"><label>資料集<select id="adminDataset">${DATASETS.map(x=>`<option value="${x}" ${x===adminDatasetName?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn" id="loadDataset">載入</button></div><div class="admin-note">這裡是系統營運資料的唯讀檢視；使用者認證秘密不會輸出。</div><div id="adminDatasetRows"></div>`;$('#loadDataset').onclick=()=>{adminDatasetName=$('#adminDataset').value;adminDatasetOffset=0;loadDataset(adminDatasetName,0)};loadDataset(adminDatasetName,adminDatasetOffset)}
async function loadDataset(name=adminDatasetName,offset=adminDatasetOffset){adminDatasetName=name;adminDatasetOffset=Math.max(0,offset);const box=$('#adminDatasetRows');box.innerHTML='<div class="admin-loading">載入中…</div>';try{const limit=200,d=await adminRequest('dataset',{name,limit,offset:adminDatasetOffset}),total=Number(d.total||0);box.innerHTML=`<div class="admin-dataset-summary">${esc(name)} · ${total.toLocaleString()} 筆</div><div class="admin-json-list">${(d.rows||[]).map(r=>`<pre>${esc(pretty(r))}</pre>`).join('')||'<div class="admin-empty">沒有資料</div>'}</div><div class="admin-pager"><button class="btn" id="adminPrevDataset" ${adminDatasetOffset===0?'disabled':''}>上一頁</button><span>${Math.min(total,adminDatasetOffset+1)}–${Math.min(total,adminDatasetOffset+limit)} / ${total}</span><button class="btn" id="adminNextDataset" ${adminDatasetOffset+limit>=total?'disabled':''}>下一頁</button></div>`;$('#adminPrevDataset').onclick=()=>loadDataset(adminDatasetName,Math.max(0,adminDatasetOffset-limit));$('#adminNextDataset').onclick=()=>loadDataset(adminDatasetName,adminDatasetOffset+limit)}catch(e){box.innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
async function boot(){if(!token())return;try{const me=await adminRequest('whoami');if(me.is_admin)installAdmin()}catch{}}
setTimeout(boot,1200);document.addEventListener('puplan:profile-changed',()=>setTimeout(boot,200));
window.PUPLAN_ADMIN={open:showAdmin};
