const $=s=>document.querySelector(s);
const messages=$('#aiMessages'),input=$('#aiInput'),send=$('#aiSend'),launch=$('#aiLaunch'),status=$('#aiStatus'),light=$('#aiLight'),mode=$('#aiModeLabel');
const asset=name=>new URL(name,import.meta.url).href;
let engine=null,browserSession=null,loading=false,contextDirty=false;
let history=[];try{history=JSON.parse(sessionStorage.getItem('puplan_assistant_history')||'[]').slice(-16)}catch{}
const state={lastDay:null,lastCourse:''};
const DAYS=window.PUPLAN_AI.DAYS,PERIODS=window.PUPLAN_AI.PERIODS;
const DAY_NUMBER={一:1,二:2,三:3,四:4,五:5};
const MODELS=['Qwen2.5-1.5B-Instruct-q4f16_1-MLC','Qwen2.5-0.5B-Instruct-q4f16_1-MLC'];
function saveHistory(){sessionStorage.setItem('puplan_assistant_history',JSON.stringify(history.slice(-16)))}
function addBubble(text,who='assistant'){const d=document.createElement('div');d.className='bubble '+(who==='user'?'me':'ai');d.append(document.createTextNode(text));messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
function setStatus(text,stateName=''){if(status)status.textContent=text;if(light)light.className='status-light '+stateName}
function currentCourses(){return window.PUPLAN_AI.courses().filter(c=>c.day>=1&&c.day<=5)}
function dayFromText(text){const m=text.match(/(?:星期|週|禮拜)([一二三四五])/);if(m)return DAY_NUMBER[m[1]];const now=new Date().getDay();if(/今天/.test(text)&&now>=1&&now<=5)return now;if(/明天/.test(text)){const d=now+1;return d>=1&&d<=5?d:null}if(/那天|那一天|那星期|那週|那呢|那/.test(text)&&state.lastDay)return state.lastDay;return null}
function courseFromText(text){const clean=s=>String(s).replace(/[()（）\s・·]/g,'').toLowerCase();const q=clean(text);const hit=currentCourses().find(c=>{const n=clean(c.name);return n.length>=2&&q.includes(n)})||currentCourses().find(c=>clean(c.name).split(/[一二三四五12345]/)[0].length>=3&&q.includes(clean(c.name).slice(0,4)));if(hit){state.lastCourse=hit.id;state.lastDay=hit.day;return hit}return currentCourses().find(c=>c.id===state.lastCourse)||null}
function formatCourse(c){return `${PERIODS[c.start-1][0]}–${PERIODS[c.end-1][1]} ${c.name}${c.room?`（${c.room}）`:''}`}
function nextClass(){const now=new Date(),d=now.getDay(),mins=now.getHours()*60+now.getMinutes(),toMin=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};if(d>=1&&d<=5){const today=currentCourses().filter(c=>c.day===d).sort((a,b)=>a.start-b.start);for(const c of today){const s=toMin(PERIODS[c.start-1][0]),e=toMin(PERIODS[c.end-1][1]);if(mins>=s&&mins<e)return{kind:'current',course:c,minutes:e-mins};if(mins<s)return{kind:'next',course:c,minutes:s-mins}}}for(let add=1;add<=7;add++){const day=((d+add-1)%7)+1;if(day<1||day>5)continue;const c=currentCourses().filter(x=>x.day===day).sort((a,b)=>a.start-b.start)[0];if(c)return{kind:'future',course:c,day}}return null}
function freeBlocks(day=null){const result=[];for(let d=day||1;d<=(day||5);d++){const busy=new Set();currentCourses().filter(c=>c.day===d).forEach(c=>{for(let p=c.start;p<=c.end;p++)busy.add(p)});let start=null;for(let p=1;p<=9;p++){if(!busy.has(p)&&start===null)start=p;if((busy.has(p)||p===9)&&start!==null){const end=busy.has(p)?p-1:p;if(end>=start)result.push({day:d,start,end});start=null}}}return result}
function blockText(b){return `${DAYS[b.day-1][1]} ${PERIODS[b.start-1][0]}–${PERIODS[b.end-1][1]}`}
function exactAnswer(text){const q=text.trim(),day=dayFromText(q);if(day)state.lastDay=day;const named=courseFromText(q);
if(/下一堂|等等上|接下來|現在上|正在上/.test(q)){const n=nextClass();if(!n)return'目前找不到下一堂課。';state.lastCourse=n.course.id;state.lastDay=n.course.day;if(n.kind==='current')return`你現在是「${n.course.name}」，大約 ${n.minutes} 分鐘後下課${n.course.room?`，教室在 ${n.course.room}`:''}。`;if(n.kind==='next')return`下一堂是「${n.course.name}」，${n.minutes} 分鐘後開始${n.course.room?`，在 ${n.course.room}`:''}。`;return`下一堂是${DAYS[n.day-1][1]}的「${n.course.name}」，${PERIODS[n.course.start-1][0]} 開始${n.course.room?`，在 ${n.course.room}`:''}。`}
if(named&&/老師|誰教|教授/.test(q))return`「${named.name}」的老師是 ${named.teacher||'課表沒有填老師'}。`;
if(named&&/教室|哪裡|在哪|地點/.test(q))return`「${named.name}」${named.room?`在 ${named.room}`:'目前課表沒有填教室'}。`;
if(day&&/(有什麼課|有哪些課|上什麼|幾堂|課表|課程)/.test(q)){const cs=currentCourses().filter(c=>c.day===day).sort((a,b)=>a.start-b.start);if(!cs.length)return`${DAYS[day-1][1]}沒有排課。`;return`${DAYS[day-1][1]}有 ${cs.length} 門：\n${cs.map((c,i)=>`${i+1}. ${formatCourse(c)}`).join('\n')}`}
if(/哪天.*(?:忙|滿|累)|最忙|最滿|最累/.test(q)){const scores=DAYS.map((_,i)=>({day:i+1,slots:currentCourses().filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0),count:currentCourses().filter(c=>c.day===i+1).length})).sort((a,b)=>b.slots-a.slots||b.count-a.count);const x=scores[0];return`${DAYS[x.day-1][1]}最滿，共 ${x.count} 門、${x.slots} 節。`}
if(/空堂|空檔|有空|空時間/.test(q)){const blocks=freeBlocks(day).filter(b=>b.end-b.start+1>=1).sort((a,b)=>(b.end-b.start)-(a.end-a.start));if(!blocks.length)return day?`${DAYS[day-1][1]}沒有找到課間空檔。`:'這週沒有找到可用空檔。';return`比較好用的空檔：\n${blocks.slice(0,5).map((b,i)=>`${i+1}. ${blockText(b)}${b.end>b.start?`（${b.end-b.start+1} 節）`:''}`).join('\n')}`}
if(/朋友|好友|共同/.test(q)&&/空|時間|有空|一起/.test(q)){const f=window.PUPLAN_AI.getSelectedFriend?.();if(!f)return'先到好友頁選一位好友，我才能比對你們兩個的課表。';const blocks=[];for(let d=1;d<=5;d++){const mine=new Set(),theirs=new Set();currentCourses().filter(c=>c.day===d).forEach(c=>{for(let p=c.start;p<=c.end;p++)mine.add(p)});f.courses.filter(c=>c.day===d).forEach(c=>{for(let p=c.start;p<=c.end;p++)theirs.add(p)});let s=null;for(let p=1;p<=9;p++){const free=!mine.has(p)&&!theirs.has(p);if(free&&s===null)s=p;if((!free||p===9)&&s!==null){const e=!free?p-1:p;if(e-s+1>=2)blocks.push({day:d,start:s,end:e});s=null}}}return blocks.length?`你和 ${f.name} 比較完整的共同空檔：\n${blocks.slice(0,5).map((b,i)=>`${i+1}. ${blockText(b)}`).join('\n')}`:`目前找不到連續兩節以上的共同空堂。`}
return''}
function planningFacts(text){const blocks=freeBlocks().sort((a,b)=>(b.end-b.start)-(a.end-a.start));const dayLoads=DAYS.map((d,i)=>({day:i+1,name:d[1],slots:currentCourses().filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0)}));const heaviest=[...dayLoads].sort((a,b)=>b.slots-a.slots)[0];return`可用資訊：最滿的是 ${heaviest.name}（${heaviest.slots} 節）。較長空檔包含 ${blocks.filter(b=>b.end-b.start+1>=2).slice(0,4).map(blockText).join('、')||'沒有連續兩節以上空堂'}。`}
function fallbackAnswer(text){const exact=exactAnswer(text);if(exact)return exact;if(/讀書|複習|作業|安排|計畫|準備/.test(text)){const blocks=freeBlocks().filter(b=>b.end-b.start+1>=2).sort((a,b)=>(b.end-b.start)-(a.end-a.start)).slice(0,3);return blocks.length?`我會先把需要專注的事情放在這幾段：\n${blocks.map((b,i)=>`${i+1}. ${blockText(b)}－${i===0?'最難的作業或考試準備':i===1?'複習與練題':'整理筆記或預習'}`).join('\n')}\n\n如果你告訴我「要準備哪一科、哪天截止」，我可以再排得更細。`:'目前課間空檔比較碎。你告訴我哪天有空、要準備什麼，我再幫你排。'}return'我有讀到你的課表，但這句我還不確定你要問哪件事。可以直接問「星期三有什麼課」、「下一堂在哪」、「這週哪段適合讀書」，或接著補一句你的目標。'}
function systemPrompt(){return`你是 PU/PLAN 裡的課表與校園規劃助理。使用繁體中文與台灣常用說法。回答要先理解使用者前面幾輪在談什麼，再回答當下問題。課表事實只能使用提供的課表資料，不得編造課名、教室、老師或時間。若資料不足就明確說不知道。規劃問題可以提出建議，但要把建議和事實分開。避免空泛勵志語、避免重複問題、避免扯到無關主題。\n\n${window.PUPLAN_AI.buildAIContext()}`}
async function initAssistant(){if(engine||browserSession)return true;if(loading)return false;loading=true;if(launch)launch.disabled=true;setStatus('正在準備進階理解…','loading');try{if('LanguageModel'in self&&self.LanguageModel?.create){browserSession=await self.LanguageModel.create({systemPrompt:systemPrompt()});mode.textContent='進階理解';setStatus('已啟用','ready');launch.textContent='已啟用';return true}if(!navigator.gpu)throw new Error('這台裝置目前不支援本機模型，仍可使用課表理解與快速規劃。');const webllm=await import('https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm/+esm');let lastError=null;for(const model of MODELS){try{engine=await webllm.CreateMLCEngine(model,{initProgressCallback:r=>{const pct=typeof r.progress==='number'?` ${Math.round(r.progress*100)}%`:'';setStatus((r.text||'下載模型')+pct,'loading')}});break}catch(e){lastError=e;engine=null}}if(!engine)throw lastError||new Error('模型載入失敗');mode.textContent='進階理解';setStatus('已啟用','ready');launch.textContent='已啟用';return true}catch(e){setStatus(e.message||'無法啟用','error');mode.textContent='基本模式';return false}finally{loading=false;if(launch)launch.disabled=false}}
async function ask(){const text=input.value.trim();if(!text)return;input.value='';addBubble(text,'user');send.disabled=true;try{const exact=exactAnswer(text);if(exact){history.push({role:'user',content:text},{role:'assistant',content:exact});saveHistory();addBubble(exact);return}if(!engine&&!browserSession){const answer=fallbackAnswer(text);history.push({role:'user',content:text},{role:'assistant',content:answer});saveHistory();addBubble(answer);return}const facts=planningFacts(text);let answer='';if(browserSession){if(contextDirty){try{browserSession.destroy?.()}catch{}browserSession=await self.LanguageModel.create({systemPrompt:systemPrompt()});contextDirty=false}const recent=history.slice(-8).map(m=>`${m.role==='user'?'使用者':'助理'}：${m.content}`).join('\n');answer=await browserSession.prompt(`${recent?`最近對話：\n${recent}\n\n`:''}${facts}\n使用者現在問：${text}`)}else{const holder=addBubble('');let streamed='';const out=await engine.chat.completions.create({messages:[{role:'system',content:systemPrompt()},{role:'system',content:facts},...history.slice(-10),{role:'user',content:text}],temperature:.35,max_tokens:520,stream:true});for await(const chunk of out){streamed+=chunk.choices?.[0]?.delta?.content||'';holder.textContent=streamed;messages.scrollTop=messages.scrollHeight}answer=streamed;if(!answer)holder.remove()}if(answer){history.push({role:'user',content:text},{role:'assistant',content:answer});saveHistory();if(browserSession)addBubble(answer)}}catch(e){const answer=fallbackAnswer(text);history.push({role:'user',content:text},{role:'assistant',content:answer});saveHistory();addBubble(answer)}finally{send.disabled=false}}
if(messages){messages.innerHTML='';addBubble('你可以直接問課表事實，也可以接著前一題往下問。像是「星期三有什麼課？」→「那星期四呢？」；我會保留這次開啟頁面的對話脈絡。')}
if(mode)mode.textContent='基本模式';if(launch)launch.textContent='啟用進階理解';setStatus('課表理解可用','ready');
launch?.addEventListener('click',initAssistant);send?.addEventListener('click',ask);input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}});document.addEventListener('puplan:courses-changed',()=>{contextDirty=true});
import(asset('./boot-v9.js')).catch(e=>console.warn('bootstrap',e));
