const q=(s)=>document.querySelector(s);
const messages=q('#aiMessages'), input=q('#aiInput'), send=q('#aiSend'), launch=q('#aiLaunch'), status=q('#aiStatus'), light=q('#aiLight'), mode=q('#aiModeLabel');
let engine=null, builtIn=null, loading=false;
const MODEL='Qwen2.5-0.5B-Instruct-q4f16_1-MLC';
function bubble(text,who='ai'){const d=document.createElement('div');d.className='bubble '+(who==='me'?'me':'ai');const mini=document.createElement('span');mini.className='mini';mini.textContent=who==='me'?'YOU':'PU/PLAN AI';d.append(mini,document.createTextNode(text));messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
function setStatus(text,state=''){status.textContent=text;light.className='status-light '+state}
async function tryBuiltIn(){try{if('LanguageModel' in self&&self.LanguageModel?.create){setStatus('偵測到瀏覽器內建 AI，正在啟動…','loading');builtIn=await self.LanguageModel.create({systemPrompt:window.PUPLAN_AI.buildAIContext()});mode.textContent='BROWSER AI';setStatus('內建 AI 已就緒','ready');launch.textContent='AI 已啟動 ✓';return true}}catch(e){console.warn('Built-in AI unavailable',e)}return false}
async function initAI(){if(engine||builtIn)return true;if(loading)return false;loading=true;launch.disabled=true;try{if(await tryBuiltIn())return true;if(!navigator.gpu)throw new Error('這個瀏覽器目前沒有 WebGPU。可先使用右側「快速分析」，或改用支援 WebGPU 的新版瀏覽器。');setStatus('載入 AI 引擎…','loading');mode.textContent='DOWNLOADING';const webllm=await import('https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm/+esm');engine=await webllm.CreateMLCEngine(MODEL,{initProgressCallback:(r)=>{let pct=typeof r.progress==='number'?` ${Math.round(r.progress*100)}%`:'';setStatus((r.text||'下載模型中')+pct,'loading')}});mode.textContent='LOCAL AI';setStatus('Local AI 已就緒','ready');launch.textContent='AI 已啟動 ✓';bubble('Local AI ready。現在可以直接用自然語言問我課表、空堂、讀書安排或好友共同時間。');return true}catch(e){console.error(e);setStatus(e.message||'AI 啟動失敗','error');mode.textContent='QUICK MODE';window.PUPLAN_AI.toast('Local AI 暫時無法啟動');return false}finally{loading=false;launch.disabled=false}}
async function ask(){let text=input.value.trim();if(!text)return;input.value='';bubble(text,'me');send.disabled=true;try{if(!engine&&!builtIn){bubble('我先用免費快速分析幫你回答。如果要更自然、更多步驟的回答，按右邊「啟動免費 Local AI」。\n\n'+quickAnswer(text));return}let context=window.PUPLAN_AI.buildAIContext();if(builtIn){try{if(builtIn.destroy)builtIn.destroy();builtIn=await self.LanguageModel.create({systemPrompt:context});let out=await builtIn.prompt(text);bubble(out||'我沒有產生內容，再問一次看看。');return}catch(e){console.warn(e)}}let holder=bubble('');let answer='';const stream=await engine.chat.completions.create({messages:[{role:'system',content:context},{role:'user',content:text}],temperature:.5,max_tokens:450,stream:true});for await(const chunk of stream){answer+=chunk.choices?.[0]?.delta?.content||'';holder.lastChild.nodeValue=answer;messages.scrollTop=messages.scrollHeight}if(!answer)holder.lastChild.nodeValue='我沒有產生內容，再問一次看看。'}catch(e){bubble('這次沒跑成功：'+(e.message||'未知錯誤')+'\n你仍可用右側免費快速分析。')}finally{send.disabled=false}}
function quickAnswer(text){let t=text.toLowerCase();if(/累|忙|滿|壓力/.test(t))return window.PUPLAN_AI.smartAnalysis('stress');if(/好友|共同|一起|朋友/.test(t))return window.PUPLAN_AI.smartAnalysis('friend');if(/讀書|複習|作業|計畫/.test(t))return window.PUPLAN_AI.smartAnalysis('study');if(/空堂|空檔|有空|時間/.test(t))return window.PUPLAN_AI.smartAnalysis('free');return '快速模式目前最擅長：課表壓力、長空堂、讀書時段、好友共同空堂。要自由聊天請先啟動 Local AI。'}
launch?.addEventListener('click',initAI);send?.addEventListener('click',ask);input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}});
if(!navigator.gpu)setStatus('快速分析可用；Local AI 需 WebGPU','');
