const DAYS=[['一','星期一'],['二','星期二'],['三','星期三'],['四','星期四'],['五','星期五']];
const PERIODS=[['08:10','09:00'],['09:10','10:00'],['10:10','11:00'],['11:10','12:00'],['13:10','14:00'],['14:10','15:00'],['15:10','16:00'],['16:10','17:00'],['17:10','18:00'],['18:05','18:55'],['19:00','19:50'],['19:55','20:45'],['20:50','21:40']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let selectedDay=Math.min(Math.max(new Date().getDay(),1),5), selectedFriend=null;
const courses=()=>read('puplan_courses',[]), friends=()=>read('puplan_friends',[]), displayName=()=>localStorage.getItem('puplan_name')||'我的課表';
const uid=()=>crypto.randomUUID?.()||String(Date.now())+Math.random().toString(36).slice(2), esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const time=c=>c.day===0||c.start===0?'時間待定':`${PERIODS[c.start-1][0]}–${PERIODS[c.end-1][1]}`;
function toast(msg){let e=$('#toast');e.textContent=msg;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),1700)}
function renderStats(){let a=courses(),scheduled=a.filter(c=>c.day>=1&&c.day<=5),td=new Date().getDay(),today=scheduled.filter(c=>c.day===td).sort((a,b)=>a.start-b.start);$('#today').textContent=today.length;$('#hours').textContent=scheduled.reduce((n,c)=>n+(c.end-c.start+1),0);$('#count').textContent=a.length;let h=new Date().getHours();$('#greet').textContent=(h<12?'早安':h<18?'下午好':'晚上好')+'，今天的課長這樣。';$('#summary').textContent=today.length?`今天 ${today.length} 門，第一堂是 ${today[0].name}，${PERIODS[today[0].start-1][0]} 開始。`:a.length?'今天沒有排課，時間是你的。':'課表還是空的。可以新增課程，或直接用圖片快速匯入。'}
function renderTabs(){let e=$('#tabs');e.innerHTML=DAYS.map((d,i)=>`<button class="${selectedDay===i+1?'on':''}" data-day="${i+1}">${d[1]}</button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderTabs();renderMobile()})}
function renderGrid(target='#grid',data=courses(),editable=true){let h='<div class="cell head" style="grid-column:1;grid-row:1"><b>節次</b><small>TIME</small></div>';DAYS.forEach((d,i)=>h+=`<div class="cell head" style="grid-column:${i+2};grid-row:1"><b>${d[1]}</b><small>WEEK</small></div>`);PERIODS.forEach((p,i)=>{h+=`<div class="cell time" style="grid-column:1;grid-row:${i+2}"><b>${i+1}</b><small>${p[0]}<br>${p[1]}</small></div>`;DAYS.forEach((_,j)=>h+=`<div class="cell" style="grid-column:${j+2};grid-row:${i+2}"></div>`)});data.filter(c=>c.day>=1&&c.day<=5).forEach(c=>h+=`<div class="course-slot" style="grid-column:${c.day+1};grid-row:${c.start+1}/span ${c.end-c.start+1}"><article class="course ${c.color||'violet'}" data-course="${esc(c.id)}"><b>${esc(c.name)}</b><small>${esc(c.teacher||'未填老師')}<br>${esc(c.room||'未填教室')}<br>${time(c)}</small></article></div>`);$(target).innerHTML=h;if(editable)$$(target+' [data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderMobile(){let a=courses().filter(c=>c.day===selectedDay&&c.day>=1).sort((a,b)=>a.start-b.start);$('#mobile').innerHTML=a.length?a.map(c=>`<article class="mobile-course ${c.color}" data-course="${c.id}"><time>${time(c)}<br>第 ${c.start}${c.end>c.start?'–'+c.end:''} 節</time><div><b>${esc(c.name)}</b><p>${esc(c.teacher||'')} · ${esc(c.room||'')}</p></div></article>`).join(''):'<div class="project-note" style="background:var(--white)">這天沒有排課。</div>';$$('#mobile [data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderMobileWeek(){let a=courses().filter(c=>c.day>=1&&c.day<=5);$('#mobileWeek').innerHTML=DAYS.map((d,i)=>{let cs=a.filter(c=>c.day===i+1).sort((x,y)=>x.start-y.start);return `<section class="week-day-block"><div class="week-day-title"><span>${d[1]}</span><small>${cs.length} COURSES</small></div><div class="week-day-courses">${cs.length?cs.map(c=>`<article class="week-mini-course ${c.color||'gray'}" data-course="${c.id}"><time>${time(c)}<br>第${c.start}${c.end>c.start?'–'+c.end:''}節</time><div><b>${esc(c.name)}</b><br><small>${esc(c.teacher||'')} · ${esc(c.room||'')}</small></div></article>`).join(''):'<small style="font-size:9px;color:var(--muted)">FREE DAY / 無課</small>'}</div></section>`}).join('');$$('#mobileWeek [data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function renderFloatingCourses(){const box=$('#floatingCourses');if(!box)return;const list=courses().filter(c=>c.day===0);box.innerHTML=list.length?list.map(c=>`<button class="project-note floating-note" data-course="${esc(c.id)}"><b>待定 / ${esc(c.name)}</b><span>${esc(c.teacher||'')} ${esc(c.room||'時間地點依最新公告')}</span></button>`).join(''):'';box.querySelectorAll('[data-course]').forEach(e=>e.onclick=()=>openCourse(e.dataset.course))}
function applyScheduleMode(mode=localStorage.getItem('puplan_schedule_mode')||'week'){document.body.classList.toggle('schedule-day-mode',mode==='day');$$('[data-schedule-mode]').forEach(b=>b.classList.toggle('on',b.dataset.scheduleMode===mode));localStorage.setItem('puplan_schedule_mode',mode)}
function render(){renderStats();renderTabs();renderGrid();renderMobileWeek();renderMobile();renderFloatingCourses();renderShare();applyScheduleMode()}
function openCourse(id){let c=id?courses().find(x=>x.id===id):null;$('#courseTitle').textContent=c?'編輯課程':'新增課程';$('#courseId').value=c?.id||'';$('#courseName').value=c?.name||'';$('#day').value=c?.day??selectedDay;$('#start').value=c?.start>0?c.start:3;$('#end').value=c?.end>0?c.end:4;toggleCourseTimeFields();$('#teacher').value=c?.teacher||'';$('#room').value=c?.room||'';$('#color').value=c?.color||['violet','blue','mint','orange','pink','lime','gray'][courses().length%7];$('#deleteCourse').hidden=!c;$('#courseDialog').showModal()}
$('#courseForm').onsubmit=e=>{e.preventDefault();let a=courses(),id=$('#courseId').value||uid(),s=+$('#start').value,en=+$('#end').value,d=+$('#day').value;if(d===0){s=0;en=0}else if(en<s)return toast('結束節次不能早於開始');let x={id,name:$('#courseName').value.trim(),day:d,start:s,end:en,teacher:$('#teacher').value.trim(),room:$('#room').value.trim(),color:$('#color').value};let hit=d===0?null:a.find(c=>c.id!==id&&c.day===d&&!(en<c.start||s>c.end));if(hit&&!confirm(`與「${hit.name}」衝堂，仍要儲存？`))return;let i=a.findIndex(c=>c.id===id);i<0?a.push(x):a[i]=x;write('puplan_courses',a);document.dispatchEvent(new CustomEvent('puplan:courses-changed',{detail:a}));$('#courseDialog').close();render();toast(i<0?'課程已新增':'課程已更新')};
$('#deleteCourse').onclick=()=>{let id=$('#courseId').value,c=courses().find(x=>x.id===id);if(c&&confirm(`刪除「${c.name}」？`)){let next=courses().filter(x=>x.id!==id);write('puplan_courses',next);document.dispatchEvent(new CustomEvent('puplan:courses-changed',{detail:next}));$('#courseDialog').close();render();toast('已刪除')}};
function encodeShare(){let id=localStorage.getItem('puplan_id')||uid();localStorage.setItem('puplan_id',id);let payload={v:1,id,name:displayName(),t:Date.now(),courses:courses()},raw=unescape(encodeURIComponent(JSON.stringify(payload)));return 'PU1-'+btoa(raw).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_')}
function decodeShare(s){s=s.trim();if(s.includes('#friend='))s=decodeURIComponent(s.split('#friend=')[1].split('&')[0]);if(!s.startsWith('PU1-'))throw Error('好友碼格式不正確');let b=s.slice(4).replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';let p=JSON.parse(decodeURIComponent(escape(atob(b))));if(!p.id||!Array.isArray(p.courses))throw Error('好友碼資料不完整');return p}
function renderShare(){let c=encodeShare();$('#code').textContent=c;$('#name').value=displayName();if($('#username'))$('#username').value=localStorage.getItem('puplan_username')||'';return c}
async function copyText(t,msg){try{await navigator.clipboard.writeText(t);toast(msg)}catch{prompt('請手動複製',t)}}
function addFriendCode(s){let p=decodeShare(s);if(p.id===localStorage.getItem('puplan_id'))throw Error('這是你自己的好友碼');let a=friends(),i=a.findIndex(x=>x.id===p.id),f={id:p.id,name:p.name||'好友',courses:p.courses,t:p.t||Date.now()};i<0?a.unshift(f):a[i]=f;write('puplan_friends',a);selectedFriend=f.id;renderFriends();return i<0?'好友已加入':'好友課表已更新'}
function renderFriends(q=''){let a=friends().filter(f=>(f.name+' '+(f.username||'')).toLowerCase().includes(q.toLowerCase()));$('#friendList').innerHTML=a.length?a.map(f=>`<div class="friend-card ${selectedFriend===f.id?'on':''}" data-friend="${f.id}"><div class="avatar">${f.avatar?`<img src="${f.avatar}" alt="">`:esc((f.name||'?')[0])}</div><div><b>${esc(f.name)}</b><small>${f.username?'@'+esc(f.username)+' · ':''}${f.courses.length} 門課 · ${new Date(f.t).toLocaleDateString('zh-TW')}</small></div></div>`).join(''):'<div class="empty" style="min-height:220px">還沒有好友</div>';$$('[data-friend]').forEach(e=>e.onclick=()=>{selectedFriend=e.dataset.friend;renderFriends(q)});let f=friends().find(x=>x.id===selectedFriend);if(!f){$('#friendView').innerHTML='<div class="empty">還沒有選擇好友<br><br>先加入一個朋友吧。</div>';return}let days=DAYS.map((d,i)=>`<div class="friend-day"><h4>${d[1]}</h4>${f.courses.filter(c=>c.day===i+1).sort((a,b)=>a.start-b.start).map(c=>`<div class="friend-course ${c.color||'gray'}"><b>${esc(c.name)}</b><br><small>${time(c)}<br>${esc(c.room||'')}</small></div>`).join('')||'<small style="font-size:9px;color:var(--muted)">無課</small>'}</div>`).join('');$('#friendView').innerHTML=`<div class="friend-top"><div class="avatar">${f.avatar?`<img src="${f.avatar}" alt="">`:esc((f.name||'?')[0])}</div><div><b>${esc(f.name)}</b><br><small style="font-size:9px;color:var(--muted)">${f.courses.length} 門課</small></div><button class="btn danger" id="removeFriend">移除</button></div><div class="friend-days">${days}</div>`;$('#removeFriend').onclick=async()=>{if(!confirm(`移除好友「${f.name}」？`))return;if(f.cloud&&window.PUPLAN_CLOUD){await window.PUPLAN_CLOUD.removeFriend(f.id);return}write('puplan_friends',friends().filter(x=>x.id!==f.id));selectedFriend=null;renderFriends();toast('好友已移除')}}
function dayCourseMinutes(day){return courses().filter(c=>c.day===day).reduce((n,c)=>n+(c.end-c.start+1)*50,0)}
function freeBlocks(data=courses(),day=null){let out=[];for(let d=day||1;d<=(day||5);d++){let busy=new Set();data.filter(c=>c.day===d).forEach(c=>{for(let i=c.start;i<=c.end;i++)busy.add(i)});let start=null;for(let i=1;i<=9;i++){if(!busy.has(i)&&start===null)start=i;if((busy.has(i)||i===9)&&start!==null){let end=(busy.has(i)?i-1:i);if(end-start+1>=2)out.push({day:d,start,end});start=null}}}return out}
function blockLabel(b){return `${DAYS[b.day-1][1]} ${PERIODS[b.start-1][0]}–${PERIODS[b.end-1][1]}`}
function commonFreeWithFriend(f){if(!f)return[];let merged=[];for(let d=1;d<=5;d++){let a=new Set(),b=new Set();courses().filter(c=>c.day===d).forEach(c=>{for(let i=c.start;i<=c.end;i++)a.add(i)});f.courses.filter(c=>c.day===d).forEach(c=>{for(let i=c.start;i<=c.end;i++)b.add(i)});let start=null;for(let i=1;i<=9;i++){let free=!a.has(i)&&!b.has(i);if(free&&start===null)start=i;if((!free||i===9)&&start!==null){let end=(!free?i-1:i);if(end-start+1>=2)merged.push({day:d,start,end});start=null}}}return merged}
function smartAnalysis(kind){let a=courses(),html='';if(kind==='stress'){let scores=DAYS.map((_,i)=>({day:i+1,n:a.filter(c=>c.day===i+1).length,slots:a.filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0)})).sort((x,y)=>y.slots-x.slots||y.n-x.n);let x=scores[0];html=`<b>${DAYS[x.day-1][1]}最滿。</b><br>共 ${x.n} 門、${x.slots} 節。${x.slots>=6?'建議這天不要再塞重度讀書。':'其實整週課量不算爆，可以把深度讀書放在其他空檔。'}`}else if(kind==='free'){let blocks=freeBlocks().sort((x,y)=>(y.end-y.start)-(x.end-x.start));html=blocks.length?`<b>最值得用的長空堂：</b><br>${blocks.slice(0,4).map((b,i)=>`${i+1}. ${blockLabel(b)}（${b.end-b.start+1} 節）`).join('<br>')}`:'<b>沒有找到連續兩節以上的空堂。</b>'}else if(kind==='study'){let blocks=freeBlocks().sort((x,y)=>(y.end-y.start)-(x.end-x.start)).slice(0,3);html=blocks.length?`<b>我會先排這 3 段：</b><br>${blocks.map((b,i)=>`${i+1}. ${blockLabel(b)} → ${i===0?'最難科目 / 作業':i===1?'複習＋題目':'整理筆記＋預習'}`).join('<br>')}<br><br>原則：先用長空堂做最吃專注力的事，晚上只留輕量收尾。`:'<b>課間空檔太碎。</b><br>建議改用下課後 60–90 分鐘的固定時段。'}else if(kind==='friend'){let f=friends().find(x=>x.id===selectedFriend)||friends()[0];if(!f)html='<b>還沒有好友。</b><br>先到「好友課表」加入朋友，我就能算共同空堂。';else{let blocks=commonFreeWithFriend(f);html=blocks.length?`<b>你和 ${esc(f.name)} 的共同長空堂：</b><br>${blocks.slice(0,5).map((b,i)=>`${i+1}. ${blockLabel(b)}`).join('<br>')}`:`<b>目前沒找到連續兩節以上的共同空堂。</b><br>可以改找單節空檔或 17:00 後。`}}$('#smartResult').innerHTML=html;return $('#smartResult').innerText}
function renderSmartOverview(){if(!$('#smartResult'))return;let a=courses();let max=DAYS.map((_,i)=>({d:i+1,s:a.filter(c=>c.day===i+1).reduce((n,c)=>n+c.end-c.start+1,0)})).sort((x,y)=>y.s-x.s)[0];$('#smartResult').innerHTML=`<b>這週 ${a.length} 門課。</b><br>${DAYS[max.d-1][1]}最滿，共 ${max.s} 節。點上面的按鈕做更細的分析。`}
function buildAIContext(){let a=courses().slice().sort((x,y)=>x.day-y.day||x.start-y.start);let f=friends().find(x=>x.id===selectedFriend);let courseText=a.map(c=>`${c.day===0?'未排定':DAYS[c.day-1][1]} ${time(c)}｜${c.name}｜${c.teacher||'未填老師'}｜${c.room||'未填教室'}`).join('\n');let friendText=f?`\n目前選中的好友：${f.name}\n${f.courses.slice().sort((x,y)=>x.day-y.day||x.start-y.start).map(c=>`${c.day===0?'未排定':DAYS[c.day-1][1]} ${time(c)}｜${c.name}`).join('\n')}`:'';return `你是 PU/PLAN 的課表助理。請用繁體中文、台灣學生口吻，簡潔但具體。不要假裝知道課表以外的事；若要估計，明確說是建議。\n\n使用者課表：\n${courseText}${friendText}\n\n可用節次時間：\n${PERIODS.map((p,i)=>`第${i+1}節 ${p[0]}-${p[1]}`).join('、')}`}
window.PUPLAN_AI={courses,friends,getSelectedFriend:()=>friends().find(x=>x.id===selectedFriend),buildAIContext,smartAnalysis,esc,time,DAYS,PERIODS,toast};window.PUPLAN_APP={courses,friends,render,renderFriends,renderShare,toast,esc,time,DAYS,PERIODS,write,read,changeView:(v)=>changeView(v),setRemoteCourses:(a)=>{write('puplan_courses',Array.isArray(a)?a:[]);render()},setCoursesFromUser:(a)=>{write('puplan_courses',Array.isArray(a)?a:[]);document.dispatchEvent(new CustomEvent('puplan:courses-changed',{detail:Array.isArray(a)?a:[]}));render()},setFriends:(a)=>{write('puplan_friends',a);renderFriends()},getSelectedFriend:()=>selectedFriend,setSelectedFriend:(id)=>{selectedFriend=id;renderFriends()}};
function changeView(v){$$('.view').forEach(x=>x.classList.toggle('on',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('on',x.dataset.view===v));let map={schedule:['MY WEEK / PU PLAN','我的課表'],friends:['FRIENDS / CHECK THEIR WEEK','好友課表'],ai:['LOCAL AI / ZERO API FEE','AI 助理'],settings:['SHARE / YOUR WEEK','分享設定']};$('#kicker').textContent=map[v][0];$('#title').textContent=map[v][1];$('#add').style.visibility=v==='schedule'?'visible':'hidden';if(v==='friends')renderFriends();if(v==='settings')renderShare();if(v==='ai')renderSmartOverview()}
$('#day').innerHTML='<option value="0">未排定 / 依公告</option>'+DAYS.map((d,i)=>`<option value="${i+1}">${d[1]}</option>`).join('');function toggleCourseTimeFields(){const off=+$('#day').value===0;$('#start').disabled=off;$('#end').disabled=off}$('#day').addEventListener('change',toggleCourseTimeFields);['start','end'].forEach(id=>$('#'+id).innerHTML=PERIODS.map((p,i)=>`<option value="${i+1}">第 ${i+1} 節　${p[0]}–${p[1]}</option>`).join(''));
render();renderFriends();$$('[data-schedule-mode]').forEach(b=>b.onclick=()=>applyScheduleMode(b.dataset.scheduleMode));$$('[data-view]').forEach(b=>b.onclick=()=>changeView(b.dataset.view));$('#add').onclick=$('#mobileAdd').onclick=()=>openCourse();$('#importSchedule')?.addEventListener('click',()=>$('#importDialog')?.showModal());$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#addFriend').onclick=()=>{if(window.PUPLAN_CLOUD?.isSignedIn()){changeView('friends');$('#cloudFriendSearch')?.focus();toast('直接搜尋名字或 @帳號')}else if(window.PUPLAN_CLOUD){window.PUPLAN_CLOUD.showGate('login')}else $('#friendDialog').showModal();};$('#friendForm').onsubmit=e=>{e.preventDefault();try{toast(addFriendCode($('#friendCode').value));$('#friendCode').value='';$('#friendDialog').close()}catch(err){toast(err.message)}};$('#search').oninput=e=>renderFriends(e.target.value);$('#saveName').onclick=async()=>{let n=$('#name').value.trim(),u=($('#username')?.value||'').trim().replace(/^@/,'');if(!n)return toast('請輸入顯示名稱');if(u&&!/^[A-Za-z0-9_.]{2,24}$/.test(u))return toast('@帳號格式不正確');if(window.PUPLAN_CLOUD?.isSignedIn()){await window.PUPLAN_CLOUD.updateProfile(n,u);return}localStorage.setItem('puplan_name',n);if(u)localStorage.setItem('puplan_username',u);renderShare();toast('名稱已儲存')};$('#copyCode').onclick=()=>copyText(renderShare(),'好友碼已複製');$('#copyLink').onclick=()=>copyText(location.origin+location.pathname+'#friend='+encodeURIComponent(renderShare()),'分享連結已複製');$('#shareTop').onclick=async()=>{let url=location.origin+location.pathname+'#friend='+encodeURIComponent(renderShare());if(navigator.share)try{await navigator.share({title:'我的 PU/PLAN 課表',text:'加我好友，看我的課表',url})}catch{}else copyText(url,'分享連結已複製')};if($('#accountChip'))$('#accountChip').onclick=()=>changeView('settings');if($('#logout'))$('#logout').onclick=()=>window.PUPLAN_CLOUD?.logout?.();$$('[data-smart]').forEach(b=>b.onclick=()=>smartAnalysis(b.dataset.smart));let m=location.hash.match(/friend=([^&]+)/);if(m)try{toast(addFriendCode(decodeURIComponent(m[1])));history.replaceState(null,'',location.pathname);changeView('friends')}catch{toast('分享連結無法讀取')}