const API='https://hrrmkrayvrgnwcroyttp.supabase.co/functions/v1/pu-plan-social';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>window.PUPLAN_APP?.esc?.(String(s??''))||String(s??'');
let currentTab='feed',currentConversation='',inboxData=[],feedData=[],pollTimer=null;
function token(){return localStorage.getItem('puplan_session')||''}
function signedIn(){return !!token()&&window.PUPLAN_CLOUD?.isSignedIn?.()}
async function request(action,payload={}){if(!signedIn())throw new Error('請先登入');const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token()}`},body:JSON.stringify({action,...payload})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'操作失敗');return data}
function avatar(p,cls='avatar'){return p?.avatar_data?`<div class="${cls}"><img src="${p.avatar_data}" alt=""></div>`:`<div class="${cls}">${esc((p?.display_name||'?')[0])}</div>`}
function timeAgo(v){const d=new Date(v),n=Date.now()-d.getTime(),m=Math.floor(n/60000);if(m<1)return'剛剛';if(m<60)return`${m} 分鐘前`;const h=Math.floor(m/60);if(h<24)return`${h} 小時前`;const days=Math.floor(h/24);if(days<7)return`${days} 天前`;return d.toLocaleDateString('zh-TW',{month:'numeric',day:'numeric'})}
function installSection(){if($('#community'))return;const section=document.createElement('section');section.id='community';section.className='view';section.innerHTML=`<div class="section-head"><div><h2>校園動態</h2><p>看看朋友近況、聊課表、約吃飯，或開一個群組討論。</p></div></div><div class="community-shell"><div class="community-tabs"><button class="on" data-community-tab="feed">動態</button><button data-community-tab="chat">聊天</button></div><div id="communityBody"></div></div>`;document.querySelector('.main')?.append(section);
const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-community-open]')){const b=document.createElement('button');b.dataset.communityOpen='1';b.textContent='03　社群';const ai=nav.querySelector('[data-view="ai"]');nav.insertBefore(b,ai);[...nav.querySelectorAll('[data-view="ai"],[data-view="settings"]')].forEach((x,i)=>{x.textContent=i===0?'04　助理':'05　設定'}) ;b.onclick=showCommunity}
const bottom=document.querySelector('.bottom');if(bottom&&!bottom.querySelector('[data-community-open]')){const b=document.createElement('button');b.dataset.communityOpen='1';b.innerHTML='03<br>社群';const ai=bottom.querySelector('[data-view="ai"]');bottom.insertBefore(b,ai);if(ai)ai.innerHTML='04<br>助理';const settings=bottom.querySelector('[data-view="settings"]');if(settings)settings.innerHTML='05<br>設定';b.onclick=showCommunity}
section.querySelectorAll('[data-community-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.communityTab));}
function showCommunity(){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id==='community'));document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('on'));document.querySelectorAll('[data-community-open]').forEach(x=>x.classList.add('on'));if($('#title'))$('#title').textContent='校園動態';if($('#kicker'))$('#kicker').textContent='';if($('#add'))$('#add').style.visibility='hidden';switchTab(currentTab);startPolling()}
function switchTab(tab){currentTab=tab;document.querySelectorAll('[data-community-tab]').forEach(x=>x.classList.toggle('on',x.dataset.communityTab===tab));tab==='feed'?renderFeedShell():renderChatShell()}
function profile(){return window.PUPLAN_CLOUD?.getProfile?.()||{display_name:'我',username:''}}
function renderFeedShell(){const root=$('#communityBody');if(!signedIn()){root.innerHTML='<div class="panel empty">登入後才能使用校園動態。</div>';return}root.innerHTML=`<div class="feed-layout"><div><section class="composer-card"><div class="composer-row">${avatar(profile())}<textarea id="postInput" maxlength="600" placeholder="分享一件今天想說的事…"></textarea></div><div class="composer-actions"><button class="btn primary" id="publishPost">發佈</button></div></section><div class="feed-list" id="feedList"><div class="panel">載入中…</div></div></div><aside class="community-side"><div class="community-note"><b>這裡不是公開廣場。</b><br>目前只有登入 PU/PLAN 的使用者能看到內容。發文請避免放電話、住址、學號等敏感資料。</div><div class="community-note">貼文以文字為主，不做轉發數字競賽；希望它比較像校園裡自然的聊天牆。</div></aside></div>`;$('#publishPost').onclick=publishPost;loadFeed()}
async function loadFeed(){try{const data=await request('feed');feedData=data.posts||[];renderFeed()}catch(e){if($('#feedList'))$('#feedList').innerHTML=`<div class="panel">${esc(e.message)}</div>`}}
function renderFeed(){const list=$('#feedList');if(!list)return;const me=profile();list.innerHTML=feedData.length?feedData.map(p=>`<article class="feed-card" data-post="${p.id}"><div class="feed-author">${avatar(p.author)}<div><b>${esc(p.author?.display_name||'使用者')}</b><small>@${esc(p.author?.username||'')} · ${timeAgo(p.created_at)}</small></div>${p.author_id===me.id?`<button class="btn danger" data-delete-post="${p.id}" style="margin-left:auto;padding:5px 8px">刪除</button>`:''}</div><div class="feed-body">${esc(p.body)}</div><div class="feed-actions"><button data-like-post="${p.id}">${p.liked?'♥':'♡'} ${p.like_count||0}</button><button data-reply-toggle="${p.id}">回覆 ${p.reply_count||0}</button></div>${p.replies?.length?`<div class="reply-list">${p.replies.map(r=>`<div class="reply-item"><b>${esc(r.author?.display_name||'使用者')}</b>${esc(r.body)}</div>`).join('')}</div>`:''}<div class="reply-composer hidden" data-reply-box="${p.id}"><input maxlength="600" placeholder="寫個回覆"><button class="btn" data-send-reply="${p.id}">送出</button></div></article>`).join(''):'<div class="panel empty">目前還沒有貼文。第一篇可以很普通，例如「今天主顧館冷氣超冷」。</div>';
list.querySelectorAll('[data-like-post]').forEach(b=>b.onclick=()=>toggleLike(b.dataset.likePost));list.querySelectorAll('[data-reply-toggle]').forEach(b=>b.onclick=()=>list.querySelector(`[data-reply-box="${b.dataset.replyToggle}"]`)?.classList.toggle('hidden'));list.querySelectorAll('[data-send-reply]').forEach(b=>b.onclick=()=>sendReply(b.dataset.sendReply));list.querySelectorAll('[data-delete-post]').forEach(b=>b.onclick=()=>deletePost(b.dataset.deletePost))}
async function publishPost(){const input=$('#postInput'),body=input?.value.trim();if(!body)return;try{$('#publishPost').disabled=true;await request('create_post',{body});input.value='';await loadFeed()}catch(e){window.PUPLAN_APP?.toast?.(e.message)}finally{$('#publishPost').disabled=false}}
async function toggleLike(id){try{await request('toggle_like',{post_id:id});await loadFeed()}catch(e){window.PUPLAN_APP?.toast?.(e.message)}}
async function sendReply(id){const box=document.querySelector(`[data-reply-box="${id}"]`),input=box?.querySelector('input'),body=input?.value.trim();if(!body)return;try{await request('reply_post',{post_id:id,body});await loadFeed()}catch(e){window.PUPLAN_APP?.toast?.(e.message)}}
async function deletePost(id){if(!confirm('刪除這篇貼文？'))return;try{await request('delete_post',{post_id:id});await loadFeed()}catch(e){window.PUPLAN_APP?.toast?.(e.message)}}
function renderChatShell(){const root=$('#communityBody');if(!signedIn()){root.innerHTML='<div class="panel empty">登入後才能使用聊天。</div>';return}root.innerHTML=`<div class="chat-layout" id="chatLayout"><section class="inbox-panel"><div class="inbox-head"><b>訊息</b><button class="btn" id="newChat">＋ 新對話</button></div><div class="inbox-list" id="inboxList"><div class="activity-empty">載入中…</div></div></section><section class="chat-panel" id="chatPanel"><div class="chat-empty">選一個對話，或建立新的私訊 / 群聊。</div></section></div>`;$('#newChat').onclick=openNewChat;loadInbox()}
function conversationName(c){if(c.kind==='group')return c.title||'群聊';const me=profile();const other=(c.members||[]).find(m=>m.user_id!==me.id)?.profile;return other?.display_name||'私訊'}
function conversationAvatar(c){if(c.kind==='group')return `<div class="avatar">${esc((c.title||'群')[0])}</div>`;const me=profile(),other=(c.members||[]).find(m=>m.user_id!==me.id)?.profile;return avatar(other)}
async function loadInbox(silent=false){try{const data=await request('inbox');inboxData=data.conversations||[];renderInbox();if(currentConversation)await openConversation(currentConversation,true)}catch(e){if(!silent&&$('#inboxList'))$('#inboxList').innerHTML=`<div class="activity-empty">${esc(e.message)}</div>`}}
function renderInbox(){const list=$('#inboxList');if(!list)return;list.innerHTML=inboxData.length?inboxData.map(c=>`<button class="inbox-item ${c.id===currentConversation?'on':''}" data-open-conversation="${c.id}">${conversationAvatar(c)}<span class="inbox-copy"><b>${esc(conversationName(c))}</b><span>${esc(c.last_message?.body||'還沒有訊息')}</span></span>${c.unread?`<i class="unread">${Math.min(99,c.unread)}</i>`:''}</button>`).join(''):'<div class="activity-empty">還沒有聊天。可以從好友開始一個私訊，或一次勾多人建立群聊。</div>';list.querySelectorAll('[data-open-conversation]').forEach(b=>b.onclick=()=>openConversation(b.dataset.openConversation))}
async function openConversation(id,silent=false){try{currentConversation=id;const data=await request('conversation',{conversation_id:id});const panel=$('#chatPanel');if(!panel)return;const c=data.conversation,profiles=new Map((data.profiles||[]).map(p=>[p.id,p])),me=profile();panel.innerHTML=`<div class="chat-head"><button class="btn" id="chatBack" style="display:none">←</button> ${esc(c.kind==='group'?(c.title||'群聊'):(data.profiles||[]).find(p=>p.id!==me.id)?.display_name||'私訊')}</div><div class="chat-messages" id="chatMessages">${(data.messages||[]).map(m=>{const mine=m.sender_id===me.id,p=profiles.get(m.sender_id);return `<div class="message-row ${mine?'mine':'theirs'}">${mine?'':`<span class="message-name">${esc(p?.display_name||'使用者')}</span>`}<div class="message-bubble">${esc(m.body)}</div><span class="message-time">${new Date(m.created_at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}</span></div>`}).join('')}</div><div class="chat-compose"><input id="messageInput" maxlength="2000" placeholder="輸入訊息"><button class="btn primary" id="sendMessage">送出</button></div>`;$('#sendMessage').onclick=sendMessage;$('#messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};$('#chatLayout')?.classList.add('has-chat');const msg=$('#chatMessages');if(msg)msg.scrollTop=msg.scrollHeight;await request('mark_read',{conversation_id:id});renderInbox();const back=$('#chatBack');if(back){back.style.display=innerWidth<=940?'inline-flex':'none';back.onclick=()=>{currentConversation='';$('#chatLayout')?.classList.remove('has-chat')}}}catch(e){if(!silent)window.PUPLAN_APP?.toast?.(e.message)}}
async function sendMessage(){const input=$('#messageInput'),body=input?.value.trim();if(!body||!currentConversation)return;try{$('#sendMessage').disabled=true;await request('send_message',{conversation_id:currentConversation,body});input.value='';await openConversation(currentConversation,true);await loadInbox(true)}catch(e){window.PUPLAN_APP?.toast?.(e.message)}finally{if($('#sendMessage'))$('#sendMessage').disabled=false}}
function openNewChat(){const friends=(window.PUPLAN_CLOUD?.getSocial?.().friends||[]).filter(f=>f.cloud);if(!friends.length)return window.PUPLAN_APP?.toast?.('先加一位好友，才能開始聊天');let d=$('#newChatDialog');if(!d){d=document.createElement('dialog');d.id='newChatDialog';d.className='new-chat-dialog';document.body.append(d)}d.innerHTML=`<div class="modal-head"><h2>開始對話</h2><button class="x" type="button">×</button></div><label class="label">群聊名稱（多人時可填）<input class="field" id="groupTitle" maxlength="80" placeholder="例如：期末專案組"></label><div class="friend-picker">${friends.map(f=>`<label class="friend-pick"><input type="checkbox" value="${f.id}">${f.avatar?`<div class="avatar"><img src="${f.avatar}" alt=""></div>`:`<div class="avatar">${esc((f.name||'?')[0])}</div>`}<span>${esc(f.name)}<small>@${esc(f.username||'')}</small></span></label>`).join('')}</div><div class="row" style="justify-content:flex-end"><button class="btn primary" id="createConversation">建立對話</button></div>`;d.querySelector('.x').onclick=()=>d.close();$('#createConversation').onclick=async()=>{const ids=[...d.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);if(!ids.length)return window.PUPLAN_APP?.toast?.('請選至少一位好友');try{const data=await request('create_chat',{user_ids:ids,title:$('#groupTitle').value.trim()});d.close();await loadInbox();await openConversation(data.conversation.id)}catch(e){window.PUPLAN_APP?.toast?.(e.message)}};d.showModal()}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(!document.hidden&&$('#community')?.classList.contains('on'))currentTab==='feed'?loadFeed():loadInbox(true)},12000)}
installSection();
document.addEventListener('puplan:profile-changed',()=>{if($('#community')?.classList.contains('on'))switchTab(currentTab)});
window.PUPLAN_COMMUNITY={show:showCommunity,openChatWith:async userId=>{showCommunity();switchTab('chat');const data=await request('create_chat',{user_ids:[userId]});await loadInbox();await openConversation(data.conversation.id)}};
