const $=s=>document.querySelector(s);
const app=window.PUPLAN_APP;
const DAYS=app.DAYS,PERIODS=app.PERIODS;
const COLORS=['violet','orange','blue','pink','mint','gray','lime'];
let file=null,previewUrl='',worker=null,busy=false,token=0,drafts=[],meta={},timer=null;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const uid=()=>crypto.randomUUID?.()||`imp-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const esc=s=>app.esc(String(s??''));
const hide=(el,v=true)=>el?.classList.toggle('hidden',!!v);
function status(p,text,detail=''){p=clamp(Number(p)||0,0,1);const bar=$('#ocrBar'),pc=$('#ocrPercent'),st=$('#ocrStatus'),hint=$('#ocrHint');if(bar)bar.style.width=`${Math.round(p*100)}%`;if(pc)pc.textContent=`${Math.round(p*100)}%`;if(st&&text)st.textContent=text;if(hint&&detail)hint.textContent=detail}
function inlineNotice(kind,title,detail){let box=$('#importInlineNotice');if(!box){box=document.createElement('div');box.id='importInlineNotice';box.className='import-inline-notice';const left=document.querySelector('.import-left');(left||$('#ocrProgress')?.parentElement)?.append(box)}box.dataset.kind=kind;box.innerHTML=`<b>${esc(title)}</b>${detail?`<span>${esc(detail)}</span>`:''}`;box.hidden=false}
function clearNotice(){const b=$('#importInlineNotice');if(b)b.hidden=true}
function clean(s=''){let x=String(s).replace(/[\r\n]+/g,' ').replace(/[｜|]/g,' / ').replace(/[（]/g,'(').replace(/[）]/g,')').replace(/\s+/g,' ').trim();for(let i=0;i<3;i++)x=x.replace(/([\u3400-\u9fff])\s+(?=[\u3400-\u9fff])/g,'$1');return x}
const norm=s=>clean(s).toLowerCase().replace(/\s+/g,'').replace(/[・·]/g,'');
function correctRoom(s=''){let t=clean(s).replace(/主[頤顧固]/g,'主顧').replace(/任[恒垣]/g,'任垣').replace(/伯[鐸铎]/g,'伯鐸');const m=t.match(/\((PH|SP|AK)[- ]?([A-Z0-9]+)\)/i);if(m){const b={PH:'主顧',SP:'伯鐸',AK:'任垣'}[m[1].toUpperCase()];if(b&&!t.includes(b))t=`${b}${m[2]}（${m[1].toUpperCase()}${m[2]}）`}return t}
function roomFrom(text=''){const t=correctRoom(text);return (t.match(/((?:主顧|伯鐸|任垣|文興|思源|方濟|格倫|至善|靜安|計中|圖書館|體育館|宜園|司鐸)[^/，,;；]{0,28}?(?:\d{2,4}|[A-Z]\d{2,4})(?:\([^)]{1,18}\))?)/i)||[])[1]?.trim()||(t.match(/([^/，,;；]{0,20}\((?:PH|SP|AK)[-A-Z0-9]*\d{2,4}\))/i)||[])[1]?.trim()||''}
function parseCell(lines){const raw=lines.map(x=>clean(x.text)).filter(Boolean);let full=clean(raw.join(' ')).replace(/\b(?:第?\d{1,2}節|\d{1,2}:\d{2}\s*[-–~]\s*\d{1,2}:\d{2})\b/g,'').trim(),room=roomFrom(full),rem=room?clean(full.replace(room,' ')):full;rem=rem.replace(/\b(?:PH|SP|AK)[- ]?\w+\b/gi,' ').trim();let name='',teacher='';const parts=rem.split(/\s*[\/／]\s*/).map(x=>x.trim()).filter(Boolean);if(parts.length>=2){name=parts.shift();teacher=clean(parts.join(' '))}else{const short=raw.slice().reverse().find(x=>/^[\u3400-\u9fff·]{2,5}$/.test(x)&&!/(大學|課表|星期|節次|學分|資管)/.test(x));if(short&&rem.endsWith(short)){teacher=short;name=rem.slice(0,-short.length).trim()}else name=rem}name=name.replace(/^\d+[.、]?\s*/,'').replace(/^(課程名稱|科目)[:：]?/,'').trim();return{name:name.slice(0,100),teacher:teacher.replace(/^(老師|教師)[:：]?/,'').trim().slice(0,50),room:correctRoom(room).slice(0,80),raw:full}}
function cluster(v,t=3){if(!v.length)return[];v=[...v].sort((a,b)=>a-b);const out=[];let a=v[0],b=v[0];for(const x of v.slice(1)){if(x<=b+t)b=x;else{out.push((a+b)/2);a=b=x}}out.push((a+b)/2);return out}
function detectGrid(c){const ctx=c.getContext('2d',{willReadFrequently:true}),w=c.width,h=c.height,d=ctx.getImageData(0,0,w,h).data,dark=(x,y)=>{const i=(y*w+x)*4;return .299*d[i]+.587*d[i+1]+.114*d[i+2]<190};const rows=[],sx=Math.max(1,Math.floor(w/800));for(let y=Math.floor(h*.04);y<Math.floor(h*.9);y++){let n=0,z=0;for(let x=0;x<w;x+=sx){z++;if(dark(x,y))n++}if(n/z>.36)rows.push(y)}const ry=cluster(rows,4);let best=null;for(let i=0;i<ry.length;i++)for(let j=i+1;j<Math.min(ry.length,i+7);j++){const gap=ry[j]-ry[i];if(gap<24||gap>150)continue;let score=0;for(let k=0;k<=15;k++){const y=ry[i]+k*gap;if(ry.some(r=>Math.abs(r-y)<Math.max(5,gap*.16)))score++}if(score>=9&&(!best||score>best.score))best={top:ry[i],rowH:gap,score}}if(!best)return null;const bottom=Math.min(h-1,best.top+best.rowH*15),cols=[],sy=Math.max(1,Math.floor((bottom-best.top)/650));for(let x=0;x<w;x++){let n=0,z=0;for(let y=Math.floor(best.top);y<bottom;y+=sy){z++;if(dark(x,y))n++}if(n/z>.45)cols.push(x)}const cx=cluster(cols,4);let lines=null,q=Infinity;for(let i=0;i<=cx.length-9;i++){const g=cx.slice(i,i+9),ds=g.slice(1).map((x,k)=>x-g[k]),mean=ds.reduce((a,b)=>a+b,0)/ds.length,cv=Math.sqrt(ds.reduce((a,b)=>a+(b-mean)**2,0)/ds.length)/mean;if(mean>28&&mean<w*.28&&cv<q){q=cv;lines=g}}if(!lines)return null;function strength(day,y){const x0=Math.floor(lines[day]+5),x1=Math.floor(lines[day+1]-5);let n=0,z=0;for(let yy=Math.round(y)-3;yy<=Math.round(y)+3;yy++)for(let x=x0;x<=x1;x+=2){if(yy>=0&&yy<h){z++;if(dark(x,yy))n++}}return z?n/z:1}return{...best,bottom,xlines:lines,boundaryStrength:strength}}
function eraseLines(c,g){const out=document.createElement('canvas');out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.drawImage(c,0,0);x.fillStyle='#fff';for(const col of g.xlines)x.fillRect(Math.round(col)-4,Math.max(0,Math.round(g.top)-4),9,Math.min(out.height-g.top,g.rowH*15+9));for(let r=0;r<=15;r++){const y=Math.round(g.top+r*g.rowH);x.fillRect(Math.max(0,Math.round(g.xlines[0])-4),y-4,Math.round(g.xlines[8]-g.xlines[0])+8,9)}return out}
function period(row){if(row>=1&&row<=4)return row;if(row>=6&&row<=14)return row-1;return null}
function spanAt(g,day,y){let r=clamp(Math.floor((y-g.top)/g.rowH),1,14);if(r===5)r=y<g.top+5.5*g.rowH?4:6;let a=r,b=r;while(a>1&&a!==6&&g.boundaryStrength(day,g.top+a*g.rowH)<.28)a--;while(b<14&&b!==4&&g.boundaryStrength(day,g.top+(b+1)*g.rowH)<.28)b++;const s=period(a),e=period(b);return s&&e?{start:s,end:e}:null}
function linesFrom(data){const out=[];const add=(text,confidence,bbox)=>{if(text?.trim()&&bbox)out.push({text:text.trim(),confidence:Number(confidence??70),bbox})};for(const b of data.blocks||[])for(const p of b.paragraphs||[])for(const l of p.lines||[])add(l.text,l.confidence??b.confidence,l.bbox);if(!out.length)for(const l of data.lines||[])add(l.text,l.confidence,l.bbox);if(!out.length)for(const w of data.words||[])add(w.text,w.confidence,w.bbox);return out}
function parseCourses(lines,g,text){const groups=new Map();for(const l of lines){const cx=(l.bbox.x0+l.bbox.x1)/2,cy=(l.bbox.y0+l.bbox.y1)/2;if(cy<g.top+g.rowH||cy>g.bottom)continue;let day=0;for(let d=1;d<=5;d++)if(cx>g.xlines[d]&&cx<g.xlines[d+1]){day=d;break}if(!day)continue;const sp=spanAt(g,day,cy);if(!sp)continue;const key=`${day}-${sp.start}-${sp.end}`;if(!groups.has(key))groups.set(key,{day,...sp,lines:[]});groups.get(key).lines.push(l)}const out=[];for(const x of groups.values()){x.lines.sort((a,b)=>a.bbox.y0-b.bbox.y0||a.bbox.x0-b.bbox.x0);const p=parseCell(x.lines);if(!p.name||/^(一|二|三|四|五|六|日|節次|午)$/.test(p.name)||/^(注意|學期總學分|表列印日期)/.test(p.name))continue;out.push({id:uid(),name:p.name,day:x.day,start:x.start,end:x.end,teacher:p.teacher,room:p.room,color:COLORS[(x.day*3+x.start)%COLORS.length],confidence:Math.round(x.lines.reduce((n,l)=>n+l.confidence,0)/x.lines.length),raw:p.raw,selected:true})}const t=clean(text);if(/專案實作\s*\(?\s*(?:二|2)\s*\)?/.test(t)&&!out.some(c=>/專案實作/.test(c.name)))out.push({id:uid(),name:'專案實作(二)',day:0,start:0,end:0,teacher:'',room:'時間地點依最新公告',color:'lime',confidence:80,raw:'辨識到無固定時段課程',selected:true});return out.sort((a,b)=>(a.day||99)-(b.day||99)||a.start-b.start)}
function parseMeta(text=''){const t=clean(text),school=(t.match(/([\u3400-\u9fff]{2,14}(?:大學|學院))/)||[])[1]||'',m=t.match(/(\d{2,3})\s*學年度.{0,40}?第\s*([12一二])\s*學期/),year=m?.[1]||'',semester=m?.[2]?({'一':'1','二':'2'}[m[2]]||m[2]):'',cm=t.match(/(?:系級|班級|班別)\s*[:：]?\s*([\u3400-\u9fffA-Za-z0-9_-]{2,20})/),className=cm?.[1]||(t.match(/(?:資管|資科|資工|企管|會計|財金|外文|西文|中文|法律|社工|觀光|化科|食營|應化|大傳)[一二三四1234][A-Za-z]?/)||[])[0]||'',credits=(t.match(/(?:學期總學分|總學分|本學期學分)\s*[:：]?\s*(\d+(?:\.\d+)?)/)||[])[1]||'';return{school,year,semester,className,credits,title:[year&&`${year} 學年度`,semester&&`第 ${semester} 學期`].filter(Boolean).join('・')}}
function same(a,b){return a&&b&&a.day===b.day&&a.start===b.start&&a.end===b.end&&norm(a.name)===norm(b.name)}
function overlap(a,b){return a&&b&&a.day>0&&a.day===b.day&&!(a.end<b.start||a.start>b.end)}
const selected=()=>drafts.filter(c=>c.selected!==false&&c.name?.trim());
function analyze(){const cur=app.courses(),merge=document.querySelector('input[name="importMode"]:checked')?.value==='merge';drafts.forEach((c,i)=>{const f=[];if((c.confidence||0)<65)f.push({type:'low',label:'需確認'});if(merge&&cur.some(x=>same(c,x)))f.push({type:'duplicate',label:'已有相同課'});else if(merge&&cur.some(x=>overlap(c,x)))f.push({type:'conflict',label:'與現有課衝堂'});const prev=drafts.slice(0,i);if(prev.some(x=>same(c,x)))f.push({type:'duplicate',label:'圖片內重複'});else if(prev.some(x=>overlap(c,x)))f.push({type:'conflict',label:'圖片內衝堂'});c.flags=f})}
function projected(){if(document.querySelector('input[name="importMode"]:checked')?.value!=='merge')return selected();const cur=app.courses(),keys=new Set(cur.map(c=>`${c.day}|${c.start}|${c.end}|${norm(c.name)}`));return[...cur,...selected().filter(c=>!keys.has(`${c.day}|${c.start}|${c.end}|${norm(c.name)}`))]}
function renderMeta(){const el=$('#importMetadata');if(!el)return;const x=[];if(meta.school)x.push(['學校',meta.school]);if(meta.title)x.push(['學期',meta.title]);if(meta.className)x.push(['系級',meta.className]);if(meta.credits)x.push(['學分',`${meta.credits} 學分`]);el.innerHTML=x.length?x.map(([k,v])=>`<div><small>${k}</small><b>${esc(v)}</b></div>`).join(''):'<div class="metadata-empty"><small>課表資訊</small><b>未可靠辨識到表頭，可先匯入課程</b></div>'}
function renderPreview(){const el=$('#importWeekPreview');if(!el)return;const all=projected();$('#importPreviewCount')&&($('#importPreviewCount').textContent=`${selected().length} 門將匯入`);el.innerHTML=DAYS.map((d,i)=>{const cs=all.filter(c=>c.day===i+1).sort((a,b)=>a.start-b.start);return`<section class="preview-day"><header><b>${d[1]}</b><span>${cs.length}</span></header><div>${cs.length?cs.map(c=>`<article class="preview-course ${c.color||'gray'}"><time>${PERIODS[c.start-1]?.[0]||''}</time><b>${esc(c.name)}</b><small>${esc(c.room||'')}</small></article>`).join(''):'<em>無課</em>'}</div></section>`}).join('')}
function summary(){const a=selected(),avg=a.length?Math.round(a.reduce((n,c)=>n+(c.confidence||0),0)/a.length):0,low=a.filter(c=>(c.confidence||0)<65).length,dup=a.filter(c=>c.flags?.some(f=>f.type==='duplicate')).length,con=a.filter(c=>c.flags?.some(f=>f.type==='conflict')).length;$('#importConfidence')&&($('#importConfidence').textContent=a.length?`${a.length}/${drafts.length} 門 · ${avg}%`:'0 門');$('#importSummary')&&($('#importSummary').innerHTML=a.length?`<b>準備匯入 ${a.length} 門課</b><span>${low?`${low} 門需要確認`:'可以直接看整週預覽'}</span>`:'<b>目前沒有選課</b><span>至少勾一門</span>');const w=[];dup&&w.push(`${dup} 門重複`);con&&w.push(`${con} 門衝堂`);low&&w.push(`${low} 門低信心`);$('#importWarning')&&($('#importWarning').innerHTML=w.length?`<b>請確認：</b>${w.join('、')}`:'<b>沒有偵測到重複或衝堂。</b>');if($('#confirmImport')){$('#confirmImport').textContent=`匯入 ${a.length} 門`;$('#confirmImport').disabled=!a.length}}
function render(){analyze();const list=$('#recognizedList');if(!list)return;const days=['未排定','星期一','星期二','星期三','星期四','星期五'],ps=['—',...PERIODS.map((p,i)=>`第 ${i+1} 節 · ${p[0]}`)];list.innerHTML=drafts.length?drafts.map((c,i)=>`<article class="recognized-card ${c.confidence<65?'needs-check':''} ${c.selected===false?'draft-off':''}" data-draft="${i}"><div class="recognized-top"><label class="draft-check"><input type="checkbox" data-select="${i}" ${c.selected===false?'':'checked'}><span></span></label><span class="recognized-num">${String(i+1).padStart(2,'0')}</span><span class="confidence-mini">${Math.round(c.confidence||0)}%</span><div class="draft-flags">${(c.flags||[]).map(f=>`<span class="draft-flag ${f.type}">${esc(f.label)}</span>`).join('')}</div><button class="recognized-remove" data-remove="${i}" type="button">×</button></div><label>課程名稱<input class="field" data-field="name" value="${esc(c.name)}"></label><div class="recognized-row"><label>星期<select class="field" data-field="day">${days.map((x,d)=>`<option value="${d}" ${c.day===d?'selected':''}>${x}</option>`).join('')}</select></label><label>開始<select class="field" data-field="start" ${c.day===0?'disabled':''}>${ps.map((x,p)=>`<option value="${p}" ${c.start===p?'selected':''}>${x}</option>`).join('')}</select></label><label>結束<select class="field" data-field="end" ${c.day===0?'disabled':''}>${ps.map((x,p)=>`<option value="${p}" ${c.end===p?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="recognized-row two"><label>老師<input class="field" data-field="teacher" value="${esc(c.teacher||'')}"></label><label>教室<input class="field" data-field="room" value="${esc(c.room||'')}"></label></div></article>`).join(''):'<div class="import-empty compact"><b>沒有找到課程</b><span>建議使用完整課表截圖，保留星期標題與格線。</span></div>';list.querySelectorAll('[data-draft]').forEach(card=>{const i=+card.dataset.draft;card.querySelectorAll('[data-field]').forEach(el=>el.onchange=el.oninput=()=>{const k=el.dataset.field;drafts[i][k]=['day','start','end'].includes(k)?+el.value:el.value;if(k==='day')return render();renderPreview();summary()})});list.querySelectorAll('[data-select]').forEach(x=>x.onchange=()=>{drafts[+x.dataset.select].selected=x.checked;render()});list.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{drafts.splice(+x.dataset.remove,1);render()});renderMeta();renderPreview();summary()}
async function decode(file){const c=document.createElement('canvas');let source,w,h,cleanup=()=>{};if('createImageBitmap'in window){try{source=await createImageBitmap(file,{imageOrientation:'from-image'});w=source.width;h=source.height;cleanup=()=>source.close?.()}catch{}}if(!source){source=await new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('這張圖片無法解碼，請改用 PNG 或 JPEG'))};img.src=url});w=source.naturalWidth||source.width;h=source.naturalHeight||source.height}const scale=w<1400?Math.min(2,1700/w):Math.min(1,2100/w);c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(source,0,0,c.width,c.height);cleanup();return c}
async function ensureTesseract(){if(window.Tesseract)return window.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('OCR 模組下載失敗，請確認網路後重試'));document.head.append(s)});return window.Tesseract}
async function getWorker(){if(worker)return worker;const T=await ensureTesseract();status(.06,'正在準備文字辨識','第一次使用需要下載繁中文字庫，可能需要幾十秒。');worker=await T.createWorker(['chi_tra','eng'],T.OEM?.LSTM_ONLY??1,{logger:m=>{const p=Number(m.progress)||0;if(m.status==='recognizing text')status(.28+.68*p,'正在辨識課表','請保持此頁開啟，完成後會自動顯示預覽。');else if(/loading|initializing/.test(m.status||''))status(.08+.18*p,'正在載入辨識模型','第一次較慢，之後會使用瀏覽器快取。')}});try{await worker.setParameters({tessedit_pageseg_mode:T.PSM?.SPARSE_TEXT??11,preserve_interword_spaces:'1',user_defined_dpi:'220'})}catch{}return worker}
async function scan(my=token){if(!file||busy||my!==token)return;busy=true;clearNotice();hide($('#ocrProgress'),false);hide($('#importResults'),true);hide($('#importEmpty'),true);$('#startOcr')&&($('#startOcr').disabled=true);status(.02,'圖片已收到','正在讀取圖片…');try{const canvas=await decode(file);if(my!==token)return;status(.08,'正在找課表格線','已成功讀取圖片。');const g=detectGrid(canvas),w=await getWorker();if(my!==token)return;let target=canvas;if(g){status(.18,'已找到課表格線','正在先移除格線，避免中文被切碎。');target=eraseLines(canvas,g)}else{inlineNotice('warn','沒有完整抓到格線','仍會先讀文字；若結果不完整，請改用包含整張表格的截圖。')}const ret=await w.recognize(target,{}, {text:true,blocks:true,lines:true,words:true});if(my!==token)return;status(.96,'正在整理辨識結果','快完成了。');meta=parseMeta(ret.data.text||'');if(!g)throw new Error('已讀到圖片，但無法定位課表格子。請使用包含星期一到星期日、節次欄與完整外框的截圖。');drafts=parseCourses(linesFrom(ret.data),g,ret.data.text||'');if(!drafts.length)throw new Error('有讀到圖片，但沒有可靠找到課程。請換更清楚的完整課表截圖。');const pu=/靜宜大學|靜宜|主顧|任垣|伯鐸/.test(ret.data.text||'');if(pu)drafts.forEach(c=>c.confidence=Math.min(99,(c.confidence||68)+6));render();hide($('#importResults'),false);status(1,'辨識完成',`找到 ${drafts.length} 門課，請確認後再匯入。`);inlineNotice('ok',`找到 ${drafts.length} 門課`,'課表尚未被修改，按「確認匯入」後才會套用。')}catch(e){if(my!==token)return;console.error('schedule import',e);status(0,'辨識沒有完成',e.message||'請換一張圖片再試。');inlineNotice('error','這次沒有辨識成功',e.message||'請換一張更清楚的課表截圖。');hide($('#importEmpty'),false);$('#importEmpty').innerHTML='<b>沒有修改你原本的課表</b><span>可以換一張圖，或按「重新辨識」再試一次。</span>'}finally{busy=false;if($('#startOcr')){$('#startOcr').disabled=false;$('#startOcr').textContent='重新辨識'}}}
function choose(f){if(!f)return;if(!f.type?.startsWith('image/'))return inlineNotice('error','檔案不是圖片','請使用 PNG、JPEG、WebP 或手機截圖。');if(f.size>20*1024*1024)return inlineNotice('error','圖片太大','單張請控制在 20MB 以下。');file=f;drafts=[];meta={};token++;clearTimeout(timer);clearNotice();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(f);if($('#importPreview'))$('#importPreview').src=previewUrl;hide($('#importDrop'),true);hide($('#importPreviewWrap'),false);hide($('#startOcr'),false);hide($('#ocrProgress'),false);hide($('#importResults'),true);hide($('#importEmpty'),false);$('#importEmpty').innerHTML='<b>已收到圖片</b><span>正在自動辨識，第一次載入中文字庫會比較久。</span>';status(.01,'圖片已收到','辨識會自動開始。');timer=setTimeout(()=>scan(token),120)}
function reset(){clearTimeout(timer);token++;file=null;drafts=[];meta={};busy=false;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';if($('#scheduleImageInput'))$('#scheduleImageInput').value='';hide($('#importDrop'),false);hide($('#importPreviewWrap'),true);hide($('#startOcr'),true);hide($('#ocrProgress'),true);hide($('#importResults'),true);hide($('#importEmpty'),false);if($('#importEmpty'))$('#importEmpty').innerHTML='<b>上傳完整課表截圖</b><span>保留星期標題、節次和完整格線，辨識會比較準。</span>';clearNotice();status(0,'準備辨識','圖片只在這台裝置處理，不會上傳到 PU/PLAN。')}
function confirmImport(){const valid=selected().map(c=>{let day=+c.day,start=+c.start,end=+c.end;if(day===0){start=0;end=0}else{start=clamp(start||1,1,13);end=clamp(end||start,start,13)}return{id:c.id||uid(),name:c.name.trim(),day,start,end,teacher:(c.teacher||'').trim(),room:correctRoom(c.room||''),color:c.color||'gray'}});if(!valid.length)return app.toast('請至少勾一門課');let next=valid;if(document.querySelector('input[name="importMode"]:checked')?.value==='merge'){const cur=app.courses(),keys=new Set(cur.map(c=>`${c.day}|${c.start}|${c.end}|${norm(c.name)}`));next=[...cur,...valid.filter(c=>!keys.has(`${c.day}|${c.start}|${c.end}|${norm(c.name)}`))]}app.setCoursesFromUser(next);app.setScheduleMetaFromUser?.(meta);$('#importDialog')?.close();app.toast(`已匯入 ${valid.length} 門課`);reset()}
const input=$('#scheduleImageInput'),drop=$('#importDrop');input?.addEventListener('change',e=>choose(e.target.files?.[0]));drop?.addEventListener('click',e=>{if(e.target===input)return;e.preventDefault();input?.click()});$('#changeImportImage')?.addEventListener('click',()=>input?.click());$('#startOcr')?.addEventListener('click',()=>scan(token));$('#confirmImport')?.addEventListener('click',confirmImport);$('#selectAllDrafts')?.addEventListener('click',()=>{drafts.forEach(c=>c.selected=true);render()});$('#clearDrafts')?.addEventListener('click',()=>{drafts.forEach(c=>c.selected=false);render()});document.querySelectorAll('input[name="importMode"]').forEach(x=>x.addEventListener('change',render));$('#cancelImport')?.addEventListener('click',()=>$('#importDialog')?.close());drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragging')});drop?.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragging');const f=[...(e.dataTransfer?.files||[])].find(x=>x.type.startsWith('image/'));choose(f)});$('#importDialog')?.addEventListener('paste',e=>{const i=[...(e.clipboardData?.items||[])].find(x=>x.type?.startsWith('image/'));if(i){e.preventDefault();choose(i.getAsFile())}});$('#importDialog')?.addEventListener('close',()=>{if(!busy)reset()});
