const $=s=>document.querySelector(s);const asset=name=>new URL(name,import.meta.url).href;let promptEvent=null,last='';
const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1);
const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
function state(){const a=window.PUPLAN_APP;if(!a)return null;const now=new Date(),d=now.getDay(),cur=now.getHours()*60+now.getMinutes(),cs=a.courses().filter(c=>c.day>=1&&c.day<=5).sort((x,y)=>x.day-y.day||x.start-y.start);if(d>=1&&d<=5){for(const c of cs.filter(x=>x.day===d)){const s=mins(a.PERIODS[c.start-1][0]),e=mins(a.PERIODS[c.end-1][1]);if(cur>=s&&cur<e)return{type:'now',c,n:e-cur};if(cur<s)return{type:'next',c,n:s-cur}}}for(let k=1;k<=7;k++){const nd=((d+k-1)%7)+1,cc=cs.find(x=>x.day===nd);if(cc)return{type:'future',c:cc,n:null,day:nd}}return null}
function render(){if(!window.PUPLAN_APP)return;const root=$('#schedule');if(!root)return;let box=$('#classPulse');if(!box){box=document.createElement('div');box.id='classPulse';box.className='class-pulse';const anchor=$('.schedule-toolbar')||root.firstElementChild;anchor?.parentNode?.insertBefore(box,anchor)}const s=state();if(!s){box.innerHTML='<div><small>WEEK STATUS</small><b>目前沒有下一堂課</b><span>今天可以自由安排。</span></div>';return}const label=s.type==='now'?`${s.n} 分鐘後下課`:s.type==='next'?`${s.n} 分鐘後上課`:`下一堂：${window.PUPLAN_APP.DAYS[s.day-1][1]}`;box.innerHTML=`<div><small>${s.type==='now'?'RIGHT NOW':s.type==='next'?'UP NEXT':'NEXT CLASS'}</small><b>${window.PUPLAN_APP.esc(s.c.name)}</b><span>${label}${s.c.room?' · '+window.PUPLAN_APP.esc(s.c.room):''}</span></div>${s.n!=null?`<strong>${s.n}<em>MIN</em></strong>`:''}`;notify(s)}
async function notify(s){if(localStorage.getItem('puplan_reminders')!=='1'||s.type!=='next'||s.n<1||s.n>10||!('Notification'in window)||Notification.permission!=='granted')return;const key=`${new Date().toDateString()}-${s.c.id}-${s.c.start}`;if(last===key||localStorage.getItem('puplan_last_reminder')===key)return;last=key;localStorage.setItem('puplan_last_reminder',key);try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(`等等要上 ${s.c.name}`,{body:`${s.n} 分鐘後上課${s.c.room?' · '+s.c.room:''}`,icon:asset('./icon.svg'),tag:key})}catch{}}
function installDialog(){let d=$('#installHelp');if(!d){d=document.createElement('dialog');d.id='installHelp';d.className='ios-install-dialog';d.innerHTML='<div class="modal-head"><h2>加入主畫面</h2><button class="x">×</button></div><div class="ios-steps"><b>1</b><span>用 Safari 打開 PU/PLAN</span><b>2</b><span>按「分享」</span><b>3</b><span>選「加入主畫面」</span><b>4</b><span>按「新增」</span></div>';document.body.append(d);d.querySelector('.x').onclick=()=>d.close()}d.showModal()}
async function install(){if(promptEvent){promptEvent.prompt();await promptEvent.userChoice;promptEvent=null;return}if(ios)return installDialog();window.PUPLAN_APP?.toast('請從瀏覽器選單選「安裝 App」或「加入主畫面」')}
function settings(){const grid=$('#settings .settings');if(!grid||$('#deviceCard'))return;const c=document.createElement('article');c.id='deviceCard';c.className='setting-card device-card';c.innerHTML='<div class="kicker">APP / REMINDERS</div><h3>手機 App 與上課提醒</h3><p>加入主畫面後更像 App；可選擇在上課前 10 分鐘提醒。</p><button class="btn lime" id="installSettings">加入主畫面</button><label class="reminder-toggle"><input type="checkbox" id="reminderToggle"><span><b>上課前 10 分鐘提醒</b><small>需要允許瀏覽器通知。</small></span></label>';grid.append(c);$('#installSettings').onclick=install;const t=$('#reminderToggle');t.checked=localStorage.getItem('puplan_reminders')==='1';t.onchange=async()=>{if(t.checked){if(!('Notification'in window)){t.checked=false;return window.PUPLAN_APP?.toast('這個瀏覽器不支援通知')}const p=await Notification.requestPermission();if(p!=='granted'){t.checked=false;return window.PUPLAN_APP?.toast('沒有取得通知權限')}}localStorage.setItem('puplan_reminders',t.checked?'1':'0');window.PUPLAN_APP?.toast(t.checked?'上課提醒已開啟':'上課提醒已關閉')}}
function init(){settings();render();setInterval(render,30000);document.addEventListener('puplan:courses-changed',render);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e});if('serviceWorker'in navigator)navigator.serviceWorker.register(asset('./sw-v9.js')).catch(()=>{})}
window.PUPLAN_APP?init():addEventListener('DOMContentLoaded',()=>setTimeout(init,250));