const $=s=>document.querySelector(s);const asset=name=>new URL(name,import.meta.url).href;let promptEvent=null,lastReminder='';
const ua=navigator.userAgent;const ios=/iPad|iPhone|iPod/.test(ua)||(/Macintosh/.test(ua)&&navigator.maxTouchPoints>1);const safari=/Safari/.test(ua)&&!/CriOS|FxiOS|EdgiOS|OPiOS|DuckDuckGo|GSA/.test(ua);const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
function state(){const a=window.PUPLAN_APP;if(!a)return null;const now=new Date(),d=now.getDay(),cur=now.getHours()*60+now.getMinutes(),cs=a.courses().filter(c=>c.day>=1&&c.day<=5).sort((x,y)=>x.day-y.day||x.start-y.start);if(d>=1&&d<=5){for(const c of cs.filter(x=>x.day===d)){const s=mins(a.PERIODS[c.start-1][0]),e=mins(a.PERIODS[c.end-1][1]);if(cur>=s&&cur<e)return{type:'now',c,n:e-cur};if(cur<s)return{type:'next',c,n:s-cur}}}for(let k=1;k<=7;k++){const nd=((d+k-1)%7)+1,cc=cs.find(x=>x.day===nd);if(cc)return{type:'future',c:cc,n:null,day:nd}}return null}
function render(){if(!window.PUPLAN_APP)return;const root=$('#schedule');if(!root)return;let box=$('#classPulse');if(!box){box=document.createElement('div');box.id='classPulse';box.className='class-pulse';const anchor=$('.schedule-toolbar')||root.firstElementChild;anchor?.parentNode?.insertBefore(box,anchor)}const s=state();if(!s){box.innerHTML='<div><small>本週狀態</small><b>目前沒有下一堂課</b><span>今天可以自由安排。</span></div>';return}const label=s.type==='now'?`${s.n} 分鐘後下課`:s.type==='next'?`${s.n} 分鐘後上課`:`下一堂在 ${window.PUPLAN_APP.DAYS[s.day-1][1]}`;box.innerHTML=`<div><small>${s.type==='now'?'正在上課':s.type==='next'?'下一堂':'之後的課'}</small><b>${window.PUPLAN_APP.esc(s.c.name)}</b><span>${label}${s.c.room?' · '+window.PUPLAN_APP.esc(s.c.room):''}</span></div>${s.n!=null?`<strong>${s.n}<em>分鐘</em></strong>`:''}`;notify(s)}
async function notify(s){if(localStorage.getItem('puplan_reminders')!=='1'||s.type!=='next'||s.n<1||s.n>10||!('Notification'in window)||Notification.permission!=='granted')return;const key=`${new Date().toDateString()}-${s.c.id}-${s.c.start}`;if(lastReminder===key||localStorage.getItem('puplan_last_reminder')===key)return;lastReminder=key;localStorage.setItem('puplan_last_reminder',key);try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(`等等要上 ${s.c.name}`,{body:`${s.n} 分鐘後上課${s.c.room?' · '+s.c.room:''}`,icon:asset('./nolu-icon.svg'),tag:key})}catch{}}
function installDialog(){let d=$('#installHelp');if(!d){d=document.createElement('dialog');d.id='installHelp';d.className='ios-install-dialog';document.body.append(d)}const current=location.href.split('#')[0];d.innerHTML=`<div class="modal-head"><h2>把 nolu 加到主畫面</h2><button class="x" type="button">×</button></div>${!safari?'<p style="font-size:11px;line-height:1.6">你現在可能是在其他 App 的內建瀏覽器。iPhone 必須先用 <b>Safari</b> 打開這個網站，才會看到「加入主畫面」。</p>':''}<div class="ios-steps"><b>1</b><span>${safari?'確認目前使用 Safari':'先複製網址，貼到 Safari 開啟'}</span><b>2</b><span>按 Safari 下方的「分享」</span><b>3</b><span>往下找到「加入主畫面」</span><b>4</b><span>按右上角「新增」</span></div><div class="row"><button class="btn" id="copyInstallUrl">複製網址</button></div>`;d.querySelector('.x').onclick=()=>d.close();d.querySelector('#copyInstallUrl').onclick=async()=>{try{await navigator.clipboard.writeText(current);window.PUPLAN_APP?.toast('網址已複製，請用 Safari 開啟')}catch{prompt('複製這個網址到 Safari',current)}};d.showModal()}
async function install(){if(standalone())return window.PUPLAN_APP?.toast('nolu 已經在主畫面');if(promptEvent){promptEvent.prompt();await promptEvent.userChoice;promptEvent=null;return}if(ios){installDialog();return}window.PUPLAN_APP?.toast('請從瀏覽器網址列或選單選「安裝應用程式」')}
function settings(){const grid=$('#settings .settings');if(!grid||$('#deviceCard'))return;const c=document.createElement('article');c.id='deviceCard';c.className='setting-card device-card';c.innerHTML=`<h3>手機主畫面與提醒</h3><p>${standalone()?'目前已用主畫面模式開啟。':'可以把 nolu 加到手機主畫面，之後會像一般 App 一樣從圖示開啟。'}</p><button class="btn" id="installSettings">${standalone()?'已加入主畫面':'加入主畫面'}</button><label class="reminder-toggle"><input type="checkbox" id="reminderToggle"><span><b>上課前 10 分鐘提醒</b><small>需要允許瀏覽器通知。</small></span></label>`;grid.append(c);$('#installSettings').onclick=install;const t=$('#reminderToggle');t.checked=localStorage.getItem('puplan_reminders')==='1';t.onchange=async()=>{if(t.checked){if(!('Notification'in window)){t.checked=false;return window.PUPLAN_APP?.toast('這個瀏覽器不支援通知')}const p=await Notification.requestPermission();if(p!=='granted'){t.checked=false;return window.PUPLAN_APP?.toast('沒有取得通知權限')}}localStorage.setItem('puplan_reminders',t.checked?'1':'0');window.PUPLAN_APP?.toast(t.checked?'上課提醒已開啟':'上課提醒已關閉')}}
async function registerWorker(){if(!('serviceWorker'in navigator))return;try{const hadController=!!navigator.serviceWorker.controller;if(hadController){navigator.serviceWorker.addEventListener('controllerchange',()=>{const key='nolu_shell_reload_20260911_replica3';if(sessionStorage.getItem(key)==='1')return;sessionStorage.setItem(key,'1');location.reload()},{once:true})}const sw=asset('./sw.js'),scope=new URL('./',sw).pathname;const reg=await navigator.serviceWorker.register(sw,{scope,updateViaCache:'none'});await reg.update().catch(()=>{})}catch(e){console.warn('service worker',e)}}
function init(){settings();render();setInterval(render,30000);document.addEventListener('puplan:courses-changed',render);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e});window.addEventListener('appinstalled',()=>{promptEvent=null;window.PUPLAN_APP?.toast('已加入主畫面')});registerWorker()}
window.PUPLAN_INSTALL={install};window.PUPLAN_APP?init():addEventListener('DOMContentLoaded',()=>setTimeout(init,250));
