const API='https://hrrmkrayvrgnwcroyttp.supabase.co/functions/v1/pu-plan-api';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=window.PUPLAN_APP;
let semesterState={semesters:[],active_semester:null,courses:[]}, socialState=null, loading=false;

function token(){return localStorage.getItem('puplan_session')||''}
function uidFromToken(){try{const p=token().split('.')[0].replace(/-/g,'+').replace(/_/g,'/');const s=p+'='.repeat((4-p.length%4)%4);return JSON.parse(decodeURIComponent(escape(atob(s)))).uid||''}catch{return''}}
async function api(action,payload={},auth=true){const headers={'Content-Type':'application/json'};if(auth&&token())headers.Authorization=`Bearer ${token()}`;let r;try{r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,...payload})})}catch{throw Error('目前連不上雲端，請稍後再試')}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'操作失敗');return d}
function esc(s=''){return app?.esc?.(String(s))||String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(s){app?.toast?.(s)}
function active(){return semesterState.active_semester||semesterState.semesters.find(x=>x.is_current)||semesterState.semesters[0]||null}
function metaFromSemester(s){if(!s)return{};const m=String(s.semester_key||'').match(/^(\d+)-(\d)$/);return {school:s.school||'',year:m?.[1]||'',semester:m?.[2]||'',className:s.class_name||'',credits:s.credits||0,title:s.label||''}}

function injectCSS(){const st=document.createElement('style');st.textContent=`
.semester-chip,.notify-chip{border:2px solid var(--ink);background:var(--white);box-shadow:3px 3px 0 var(--ink);min-height:40px;font-weight:900}.semester-chip{padding:7px 10px;display:flex;align-items:center;gap:8px;max-width:220px}.semester-chip span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.semester-chip b{font-size:9px;background:var(--lime);border:1.5px solid var(--ink);padding:3px 5px}.notify-wrap{position:relative}.notify-chip{width:42px;display:grid;place-items:center;position:relative;font-size:17px}.notify-badge{position:absolute;right:-7px;top:-8px;min-width:20px;height:20px;padding:0 5px;border:2px solid var(--ink);background:var(--pink);font-size:9px;display:grid;place-items:center}.notify-pop{position:absolute;z-index:80;right:0;top:50px;width:min(360px,calc(100vw - 28px));border:2px solid var(--ink);background:var(--white);box-shadow:5px 5px 0 var(--ink);padding:11px;display:none}.notify-pop.on{display:block}.notify-head{display:flex;align-items:center;justify-content:space-between;border-bottom:2px dashed var(--ink);padding-bottom:8px;margin-bottom:8px}.notify-item{border:2px solid var(--ink);padding:9px;margin-top:7px;background:var(--paper);font-size:10px;line-height:1.5}.notify-item b{display:block;font-size:11px}.notify-empty{padding:22px;text-align:center;color:var(--muted);font-size:10px}
.nr-dialog{border:2px solid var(--ink);padding:0;background:var(--white);width:min(720px,calc(100vw - 20px));box-shadow:8px 8px 0 var(--ink)}.nr-dialog::backdrop{background:#1118}.nr-shell{padding:18px}.nr-title{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;border-bottom:2px solid var(--ink);padding-bottom:12px;margin-bottom:14px}.nr-title h2{margin:2px 0 0;font-size:26px;letter-spacing:-.04em}.nr-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.nr-grid .full{grid-column:1/-1}.nr-label{font-size:10px;font-weight:850;display:grid;gap:5px}.nr-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:14px}.semester-list{display:grid;gap:8px;margin-top:12px}.semester-row{border:2px solid var(--ink);padding:10px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;background:var(--paper)}.semester-row.current{background:var(--lime)}.semester-row b{font-size:11px}.semester-row small{display:block;margin-top:3px;font-size:8.5px;color:var(--muted)}.semester-row-actions{display:flex;gap:5px}.mini-action{border:2px solid var(--ink);background:var(--white);padding:6px 8px;font-size:8px;font-weight:900}.onboard-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-bottom:14px}.onboard-steps span{height:7px;border:1.5px solid var(--ink);background:var(--soft)}.onboard-steps span.on{background:var(--lime)}.onboard-choice{display:grid;grid-template-columns:1fr 1fr;gap:10px}.onboard-choice button{min-height:110px;border:2px solid var(--ink);background:var(--paper);padding:14px;text-align:left;font-weight:900}.onboard-choice button:first-child{background:var(--blue)}.recovery-code{border:2px solid var(--ink);background:var(--ink);color:#fff;padding:14px;font:700 18px ui-monospace,monospace;letter-spacing:.08em;text-align:center;word-break:break-all}.account-tools{margin-top:14px;border:2px solid var(--ink);padding:14px;background:var(--paper)}.account-tools h3{margin:3px 0 8px}.account-tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.forgot-link{border:0;background:transparent;text-decoration:underline;font-size:9px;font-weight:850;color:var(--muted);justify-self:start;padding:0}.format-badge{display:inline-block;margin-top:8px;border:2px solid var(--ink);background:var(--blue);padding:5px 8px;font-size:8px;font-weight:900}.nr-muted{font-size:9px;color:var(--muted);line-height:1.6}
@media(max-width:680px){.semester-chip span{display:none}.semester-chip{width:42px;padding:6px;justify-content:center}.semester-chip b{font-size:8px}.nr-grid,.onboard-choice,.account-tool-grid{grid-template-columns:1fr}.nr-grid .full{grid-column:auto}.nr-dialog{width:calc(100vw - 12px);max-height:92vh;overflow:auto}.notify-pop{position:fixed;left:8px;right:8px;top:auto;bottom:78px;width:auto}.semester-row{grid-template-columns:1fr}.semester-row-actions{justify-content:flex-start}}
`;document.head.appendChild(st)}

function makeDialogs(){document.body.insertAdjacentHTML('beforeend',`
<dialog id="semesterDialog" class="nr-dialog"><div class="nr-shell"><div class="nr-title"><div><div class="kicker">SEMESTERS / SWITCH FAST</div><h2>學期管理</h2></div><button class="x" data-nr-close="semesterDialog">×</button></div><div id="semesterList" class="semester-list"></div><div style="border-top:2px dashed var(--ink);margin-top:14px;padding-top:14px"><div class="kicker">ADD / EDIT</div><div class="nr-grid" style="margin-top:8px"><label class="nr-label">學年度<input class="field" id="nrYear" inputmode="numeric" placeholder="115"></label><label class="nr-label">學期<select class="field" id="nrTerm"><option value="1">第 1 學期</option><option value="2">第 2 學期</option></select></label><label class="nr-label full">學校<input class="field" id="nrSchool" placeholder="例如：靜宜大學"></label><label class="nr-label">系所<input class="field" id="nrDept" placeholder="資訊管理學系"></label><label class="nr-label">班級<input class="field" id="nrClass" placeholder="資管四B"></label><label class="nr-label">學分<input class="field" id="nrCredits" type="number" min="0" max="60" placeholder="18"></label></div><div class="nr-actions"><button class="btn" id="nrFillCurrent">帶入目前資料</button><button class="btn lime" id="nrSaveSemester">儲存並切換</button></div></div></div></dialog>
<dialog id="onboardDialog" class="nr-dialog"><div class="nr-shell"><div class="onboard-steps"><span class="on"></span><span></span><span></span></div><div class="nr-title"><div><div class="kicker">WELCOME / SET YOUR WEEK</div><h2>先把你的學期設定好。</h2></div></div><p class="nr-muted">這些資料只用來整理你自己的課表，不會公開 Email。之後都能修改。</p><div class="nr-grid"><label class="nr-label full">學校<input class="field" id="obSchool" placeholder="例如：靜宜大學"></label><label class="nr-label">學年度<input class="field" id="obYear" inputmode="numeric" placeholder="115"></label><label class="nr-label">學期<select class="field" id="obTerm"><option value="1">第 1 學期</option><option value="2">第 2 學期</option></select></label><label class="nr-label">系所<input class="field" id="obDept" placeholder="資訊管理學系"></label><label class="nr-label">班級<input class="field" id="obClass" placeholder="資管四B"></label><label class="nr-label">學分<input class="field" id="obCredits" type="number" min="0" max="60" placeholder="18"></label></div><div class="nr-actions"><button class="btn" id="obSkip">先跳過</button><button class="btn primary" id="obNext">下一步 →</button></div></div></dialog>
<dialog id="onboardChoiceDialog" class="nr-dialog"><div class="nr-shell"><div class="onboard-steps"><span class="on"></span><span class="on"></span><span></span></div><div class="nr-title"><div><div class="kicker">HOW TO START</div><h2>把課表放進來。</h2></div></div><div class="onboard-choice"><button id="obImport"><span class="kicker">FASTEST</span><br><br>⇧ 上傳課表截圖<br><small>自動辨識學校、學期、課程與教室</small></button><button id="obEmpty"><span class="kicker">MANUAL</span><br><br>＋ 從空白開始<br><small>一門一門加入自己的課</small></button></div></div></dialog>
<dialog id="forgotDialog" class="nr-dialog"><div class="nr-shell"><div class="nr-title"><div><div class="kicker">ACCOUNT RECOVERY</div><h2>忘記密碼</h2></div><button class="x" data-nr-close="forgotDialog">×</button></div><p class="nr-muted">目前免費版使用「帳號救援碼」重設密碼，不依賴付費寄信服務。登入後可以先產生並保存一組救援碼。</p><div class="nr-grid"><label class="nr-label full">Email<input class="field" id="fpEmail" type="email"></label><label class="nr-label full">帳號救援碼<input class="field" id="fpCode" placeholder="XXXX-XXXX-XXXX-XXXX"></label><label class="nr-label full">新密碼<input class="field" id="fpPassword" type="password" minlength="8"></label></div><div class="nr-actions"><button class="btn primary" id="fpSubmit">重設密碼</button></div></div></dialog>
<dialog id="recoveryDialog" class="nr-dialog"><div class="nr-shell"><div class="nr-title"><div><div class="kicker">SAVE THIS ONCE</div><h2>你的帳號救援碼</h2></div><button class="x" data-nr-close="recoveryDialog">×</button></div><p class="nr-muted">這組碼只顯示這一次。建議存進密碼管理器；產生新碼後，舊碼會立即失效。</p><div class="recovery-code" id="recoveryCode">—</div><div class="nr-actions"><button class="btn lime" id="copyRecovery">複製救援碼</button></div></div></dialog>`);
$$('[data-nr-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.nrClose)?.close())}

function addTopControls(){const actions=$('.topbar .actions');if(!actions||$('#semesterChip'))return;actions.insertAdjacentHTML('afterbegin',`<div class="notify-wrap"><button class="notify-chip" id="notifyChip" title="通知">♢<span class="notify-badge hidden" id="notifyBadge">0</span></button><div class="notify-pop" id="notifyPop"><div class="notify-head"><b>通知中心</b><button class="mini-action" id="notifyRefresh">更新</button></div><div id="notifyList" class="notify-empty">載入中…</div></div></div><button class="semester-chip" id="semesterChip" title="切換學期"><b id="semesterTiny">—</b><span id="semesterChipText">目前學期</span></button>`);$('#semesterChip').onclick=()=>{renderSemesters();$('#semesterDialog').showModal()};$('#notifyChip').onclick=e=>{e.stopPropagation();$('#notifyPop').classList.toggle('on');if($('#notifyPop').classList.contains('on'))refreshNotifications()};$('#notifyRefresh').onclick=refreshNotifications;document.addEventListener('click',e=>{if(!e.target.closest('.notify-wrap'))$('#notifyPop')?.classList.remove('on')})}

function formatSemester(s){if(!s)return'目前學期';return s.label||s.semester_key||'目前學期'}
function renderSemesterChip(){const s=active();if($('#semesterChipText'))$('#semesterChipText').textContent=formatSemester(s);if($('#semesterTiny'))$('#semesterTiny').textContent=(s?.semester_key||'—').replace('-','/')}
function fillForm(prefix,s=active()){const m=String(s?.semester_key||'').match(/^(\d+)-(\d)$/);$('#'+prefix+'Year').value=m?.[1]||'';$('#'+prefix+'Term').value=m?.[2]||'1';$('#'+prefix+'School').value=s?.school||'';$('#'+prefix+'Dept').value=s?.department||'';$('#'+prefix+'Class').value=s?.class_name||'';$('#'+prefix+'Credits').value=s?.credits||''}
function formPayload(prefix){const year=$('#'+prefix+'Year').value.trim(),term=$('#'+prefix+'Term').value;return {semester_key:`${year}-${term}`,label:`${year} 學年度・第 ${term} 學期`,school:$('#'+prefix+'School').value.trim(),department:$('#'+prefix+'Dept').value.trim(),class_name:$('#'+prefix+'Class').value.trim(),credits:Number($('#'+prefix+'Credits').value)||0,set_current:true}}
function renderSemesters(){const box=$('#semesterList');if(!box)return;box.innerHTML=semesterState.semesters.length?semesterState.semesters.map(s=>`<div class="semester-row ${s.is_current?'current':''}"><div><b>${esc(formatSemester(s))}${s.is_current?' · NOW':''}</b><small>${esc([s.school,s.class_name,s.credits?`${s.credits} 學分`:'' ].filter(Boolean).join(' · ')||'尚未填學期資料')}</small></div><div class="semester-row-actions">${s.is_current?'':`<button class="mini-action" data-switch-sem="${esc(s.semester_key)}">切換</button>`}${semesterState.semesters.length>1?`<button class="mini-action" data-delete-sem="${esc(s.semester_key)}">刪除</button>`:''}</div></div>`).join(''):'<div class="notify-empty">還沒有學期資料</div>';box.querySelectorAll('[data-switch-sem]').forEach(b=>b.onclick=()=>switchSemester(b.dataset.switchSem));box.querySelectorAll('[data-delete-sem]').forEach(b=>b.onclick=()=>deleteSemester(b.dataset.deleteSem))}
async function loadSemesters(){if(!token()||loading)return;loading=true;try{const d=await api('semesters');semesterState=d;localStorage.setItem('puplan_semesters',JSON.stringify(d.semesters||[]));localStorage.setItem('puplan_active_semester',d.active_semester?.semester_key||'');renderSemesterChip();app?.setRemoteMeta?.(metaFromSemester(d.active_semester));maybeOnboard()}catch(e){console.warn(e)}finally{loading=false}}
async function switchSemester(key){try{const d=await api('switch_semester',{semester_key:key});semesterState=d;app?.setRemoteCourses?.(d.courses||[]);app?.setRemoteMeta?.(metaFromSemester(d.active_semester));renderSemesterChip();renderSemesters();$('#semesterDialog').close();toast(`已切到 ${formatSemester(d.active_semester)}`)}catch(e){toast(e.message)}}
async function deleteSemester(key){if(!confirm('刪除這個學期？課表也會一起刪除。'))return;try{const d=await api('delete_semester',{semester_key:key});semesterState=d;app?.setRemoteCourses?.(d.courses||[]);app?.setRemoteMeta?.(metaFromSemester(d.active_semester));renderSemesterChip();renderSemesters();toast('學期已刪除')}catch(e){toast(e.message)}}
async function saveSemester(payload,close=true){if(!/^\d{2,3}-[12]$/.test(payload.semester_key))return toast('請輸入正確學年度');try{const d=await api('upsert_semester',payload);semesterState=d;app?.setRemoteCourses?.(d.courses||[]);app?.setRemoteMeta?.(metaFromSemester(d.active_semester));renderSemesterChip();renderSemesters();if(close)$('#semesterDialog')?.close();toast('學期已儲存');return d}catch(e){toast(e.message)}}

function maybeOnboard(){const id=uidFromToken();if(!id)return;const done=localStorage.getItem('puplan_onboarded_'+id)==='1',s=active();if(done)return;const blank=!app?.courses?.().length&&!s?.school&&!s?.class_name;if(blank){fillForm('ob',s);setTimeout(()=>$('#onboardDialog')?.showModal(),200)}else localStorage.setItem('puplan_onboarded_'+id,'1')}
async function completeOnboardMeta(){const p=formPayload('ob');const d=await saveSemester(p,false);if(!d)return;localStorage.setItem('puplan_onboarded_'+uidFromToken(),'1');$('#onboardDialog').close();$('#onboardChoiceDialog').showModal()}

function addAccountTools(){const card=$('.profile-editor');if(!card||$('#accountTools'))return;card.insertAdjacentHTML('beforeend',`<div class="account-tools" id="accountTools"><div class="kicker">ACCOUNT / RECOVERY</div><h3>帳號安全</h3><p class="nr-muted">免費版先使用救援碼做「忘記密碼」保護；不會把密碼寄到 Email。</p><div class="account-tool-grid"><button class="btn" id="makeRecovery">產生 / 更新救援碼</button><button class="btn" id="changePasswordBtn">變更密碼</button></div><div id="changePasswordBox" class="hidden" style="margin-top:10px"><div class="nr-grid"><label class="nr-label full">目前密碼<input class="field" id="cpCurrent" type="password"></label><label class="nr-label full">新密碼<input class="field" id="cpNext" type="password" minlength="8"></label></div><button class="btn primary" id="cpSubmit" style="width:100%;margin-top:8px">更新密碼</button></div></div>`);$('#makeRecovery').onclick=rotateRecovery;$('#changePasswordBtn').onclick=()=>$('#changePasswordBox').classList.toggle('hidden');$('#cpSubmit').onclick=changePassword}
function addForgotLink(){const form=$('#loginForm');if(!form||$('#forgotPasswordLink'))return;const b=document.createElement('button');b.type='button';b.id='forgotPasswordLink';b.className='forgot-link';b.textContent='忘記密碼？用帳號救援碼重設';b.onclick=()=>$('#forgotDialog').showModal();form.appendChild(b)}
async function rotateRecovery(){try{const d=await api('rotate_recovery_code');$('#recoveryCode').textContent=d.recovery_code;$('#recoveryDialog').showModal()}catch(e){toast(e.message)}}
async function changePassword(){const current_password=$('#cpCurrent').value,new_password=$('#cpNext').value;if(new_password.length<8)return toast('新密碼至少 8 個字元');try{await api('change_password',{current_password,new_password});$('#cpCurrent').value='';$('#cpNext').value='';$('#changePasswordBox').classList.add('hidden');toast('密碼已更新')}catch(e){toast(e.message)}}
async function recoverPassword(){const email=$('#fpEmail').value.trim(),recovery_code=$('#fpCode').value.trim(),new_password=$('#fpPassword').value;if(new_password.length<8)return toast('新密碼至少 8 個字元');try{const d=await api('recover_password',{email,recovery_code,new_password},false);$('#forgotDialog').close();toast(d.message||'密碼已重設')}catch(e){toast(e.message)}}

function profileMap(s){return new Map((s?.profiles||[]).map(p=>[p.id,p]))}
function notificationItems(s){if(!s)return[];const uid=uidFromToken(),pmap=profileMap(s),items=[];(s.relationships||[]).filter(r=>r.status==='pending'&&r.addressee_id===uid).forEach(r=>{const p=pmap.get(r.requester_id)||{};items.push({title:`${p.display_name||'有人'} 想加你好友`,sub:p.username?`@${p.username}`:'好友邀請',view:'friends'})});(s.meetups||[]).filter(m=>m.status==='pending'&&m.invitee_id===uid).forEach(m=>{const p=pmap.get(m.creator_id)||{};items.push({title:`${p.display_name||'好友'} 約你${m.kind==='meal'?'吃飯':'讀書'}`,sub:`星期${' 一二三四五'[m.day]||m.day} · 第 ${m.start_period}${m.end_period>m.start_period?'–'+m.end_period:''} 節`,view:'friends'})});return items}
function renderNotifications(){const items=notificationItems(socialState),box=$('#notifyList'),badge=$('#notifyBadge');if(badge){badge.textContent=items.length;badge.classList.toggle('hidden',!items.length)}if(!box)return;box.className=items.length?'':'notify-empty';box.innerHTML=items.length?items.map(x=>`<button class="notify-item" data-notify-view="${x.view}"><b>${esc(x.title)}</b><span>${esc(x.sub)}</span></button>`).join(''):'目前沒有待處理通知。';box.querySelectorAll('[data-notify-view]').forEach(b=>b.onclick=()=>{app?.changeView?.(b.dataset.notifyView);$('#notifyPop').classList.remove('on')})}
async function refreshNotifications(){if(!token())return;try{const d=await api('social');socialState=d.social;renderNotifications()}catch(e){console.warn(e)}}

function observeImportFormat(){const box=$('#importMetadata');if(!box)return;const update=()=>{const text=box.innerText||'';let label='GENERIC GRID';if(/靜宜大學/.test(text))label='PU / 靜宜大學專用解析';else if(/元智大學/.test(text))label='YZU / 元智大學格式偵測';else if(/逢甲大學/.test(text))label='FCU / 逢甲大學格式偵測';else if(/東海大學/.test(text))label='THU / 東海大學格式偵測';let badge=$('#formatBadge');if(!badge){badge=document.createElement('span');badge.id='formatBadge';badge.className='format-badge';box.parentElement?.insertBefore(badge,box.nextSibling)}badge.textContent=label};new MutationObserver(update).observe(box,{childList:true,subtree:true,characterData:true});update()}

function syncImportedMeta(){if(!token())return;setTimeout(async()=>{const m=app?.scheduleMeta?.()||{};const s=active();if(!s||(!m.school&&!m.year&&!m.semester&&!m.className&&!m.credits))return;const year=m.year||String(s.semester_key||'').split('-')[0],term=m.semester||String(s.semester_key||'').split('-')[1]||'1';try{const d=await api('upsert_semester',{semester_key:`${year}-${term}`,label:m.title||`${year} 學年度・第 ${term} 學期`,school:m.school||s.school||'',department:s.department||'',class_name:m.className||s.class_name||'',credits:Number(m.credits||s.credits||0),set_current:true});semesterState=d;renderSemesterChip()}catch(e){console.warn(e)}},700)}

function bind(){addTopControls();makeDialogs();addAccountTools();addForgotLink();observeImportFormat();$('#nrFillCurrent').onclick=()=>fillForm('nr',active());$('#nrSaveSemester').onclick=()=>saveSemester(formPayload('nr'));$('#obNext').onclick=completeOnboardMeta;$('#obSkip').onclick=()=>{localStorage.setItem('puplan_onboarded_'+uidFromToken(),'1');$('#onboardDialog').close()};$('#obImport').onclick=()=>{$('#onboardChoiceDialog').close();$('#importSchedule')?.click()};$('#obEmpty').onclick=()=>{$('#onboardChoiceDialog').close();$('#add')?.click()};$('#fpSubmit').onclick=recoverPassword;$('#copyRecovery').onclick=async()=>{const t=$('#recoveryCode').textContent;try{await navigator.clipboard.writeText(t);toast('救援碼已複製')}catch{prompt('請複製救援碼',t)}};document.addEventListener('puplan:social-changed',e=>{socialState=e.detail;renderNotifications()});document.addEventListener('puplan:courses-changed',syncImportedMeta);const obs=new MutationObserver(()=>{addTopControls();addAccountTools();addForgotLink()});obs.observe(document.body,{childList:true,subtree:true});setInterval(()=>{if(token())loadSemesters()},12000);setTimeout(()=>{if(token()){loadSemesters();refreshNotifications()}},700)}

injectCSS();bind();
window.PUPLAN_NEXT={loadSemesters,refreshNotifications,openSemesters:()=>{$('#semesterDialog').showModal();renderSemesters()}};
